namespace PromptTemplate.Generator;

[Generator]
public sealed class PromptTemplateGenerator : AttributeRegistrationGeneratorBase<PromptTemplateGenerator.PromptTemplateInfo>
{
    protected override string AttributeFullName => "JoinCode.Abstractions.Attributes.PromptTemplateAttribute";

    protected override PromptTemplateInfo? ExtractInfo(INamedTypeSymbol typeSymbol, AttributeData attr, Compilation compilation)
    {
        var name = AttributeScanner.GetStringNamedArg(attr, "Name");
        var category = AttributeScanner.GetIntNamedArg(attr, "Category");
        var description = AttributeScanner.GetStringNamedArg(attr, "Description") ?? "";
        var contentMember = AttributeScanner.GetStringNamedArg(attr, "ContentMember") ?? "";
        var hasParameters = AttributeScanner.GetBoolNamedArg(attr, "HasParameters");

        if (string.IsNullOrEmpty(name))
            return null;

        string contentMethod = "";
        bool isFieldAccess = false;

        if (!hasParameters)
        {
            if (!string.IsNullOrEmpty(contentMember))
            {
                contentMethod = contentMember;
                var isMethod = AttributeScanner.HasParameterlessStaticMethod(typeSymbol, contentMember);
                var isField = AttributeScanner.HasStaticStringField(typeSymbol, contentMember);
                isFieldAccess = isField && !isMethod;

                if (!isMethod && !isField)
                    return null;
            }
            else
            {
                if (AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetContent"))
                {
                    contentMethod = "GetContent";
                    isFieldAccess = false;
                }
                else if (AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetPrompt"))
                {
                    contentMethod = "GetPrompt";
                    isFieldAccess = false;
                }
                else if (AttributeScanner.HasStaticStringField(typeSymbol, "Prompt"))
                {
                    contentMethod = "Prompt";
                    isFieldAccess = true;
                }
                else if (AttributeScanner.HasStaticStringField(typeSymbol, "SystemPrompt"))
                {
                    contentMethod = "SystemPrompt";
                    isFieldAccess = true;
                }
                else
                {
                    return null;
                }
            }
        }

        return new PromptTemplateInfo(
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString(),
            name!,
            category,
            description,
            contentMethod,
            isFieldAccess,
            hasParameters);
    }

    protected override void GenerateRegistration(SourceProductionContext context, ImmutableArray<PromptTemplateInfo> infos)
    {
        var orderedInfos = infos.OrderBy(i => i.Category).ThenBy(i => i.Name).ToList();

        if (orderedInfos.Count == 0)
            return;

        var className = InferClassName(orderedInfos);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JoinCode.Abstractions.Prompts;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// 提示词模板注册表 — 由 PromptTemplateGenerator 自动生成");
        sb.AppendLine("/// 根据模板名称查找内容，用于独立 LLM 调用的 system prompt");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据模板名称获取内容，无则返回 null");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string? GetContent(string templateName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return templateName switch");
        sb.AppendLine("        {");

        foreach (var info in orderedInfos)
        {
            if (info.HasParameters) continue;

            var fqn = info.FullyQualifiedName;
            if (info.IsFieldAccess)
                sb.AppendLine($"            \"{info.Name}\" => {fqn}.{info.ContentMethod},");
            else
                sb.AppendLine($"            \"{info.Name}\" => {fqn}.{info.ContentMethod}(),");
        }

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取所有已注册的提示词模板信息");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEnumerable<(string Name, string Category, string Description, bool HasParameters)> GetAllTemplates()");
        sb.AppendLine("    {");

        foreach (var info in orderedInfos)
        {
            var categoryName = ((PromptTemplateCategoryValue)info.Category).ToString();
            var escaped = info.Description.Replace("\"", "\\\"");
            sb.AppendLine($"        yield return (\"{info.Name}\", \"{categoryName}\", \"{escaped}\", {info.HasParameters.ToString().ToLowerInvariant()});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string InferClassName(List<PromptTemplateInfo> infos)
    {
        var categories = infos.Select(i => (PromptTemplateCategoryValue)i.Category).Distinct().ToList();

        if (categories.Count == 1)
        {
            return categories[0] switch
            {
                PromptTemplateCategoryValue.Memory or PromptTemplateCategoryValue.Agent or PromptTemplateCategoryValue.Plan => "BrainPromptTemplates",
                PromptTemplateCategoryValue.Dream => "DreamPromptTemplates",
                PromptTemplateCategoryValue.Mcp => "McpPromptTemplates",
                PromptTemplateCategoryValue.Skill => "HandsPromptTemplates",
                PromptTemplateCategoryValue.Goal => "ClockPromptTemplates",
                PromptTemplateCategoryValue.System => "SystemPromptTemplates",
                _ => "PromptTemplates"
            };
        }

        var categoryNames = categories.Select(c => c.ToString()).ToList();
        if (categoryNames.Contains("Memory") || categoryNames.Contains("Agent") || categoryNames.Contains("Plan"))
            return "BrainPromptTemplates";
        if (categoryNames.Contains("Skill"))
            return "HandsPromptTemplates";

        return "PromptTemplates";
    }

    private enum PromptTemplateCategoryValue
    {
        Memory = 0,
        Agent = 1,
        System = 2,
        Dream = 3,
        Mcp = 4,
        Skill = 5,
        Plan = 6,
        Goal = 7
    }

    internal sealed class PromptTemplateInfo
    {
        public string FullyQualifiedName { get; }
        public string TypeName { get; }
        public string Namespace { get; }
        public string Name { get; }
        public int Category { get; }
        public string Description { get; }
        public string ContentMethod { get; }
        public bool IsFieldAccess { get; }
        public bool HasParameters { get; }

        public PromptTemplateInfo(
            string fullyQualifiedName, string typeName, string ns,
            string name, int category, string description,
            string contentMethod, bool isFieldAccess, bool hasParameters)
        {
            FullyQualifiedName = fullyQualifiedName;
            TypeName = typeName;
            Namespace = ns;
            Name = name;
            Category = category;
            Description = description;
            ContentMethod = contentMethod;
            IsFieldAccess = isFieldAccess;
            HasParameters = hasParameters;
        }
    }
}
