
namespace ConstructorInjection.Generator;

[Generator]
public sealed class ConstructorInjectionGenerator : IIncrementalGenerator
{
    private const string InjectAttributeFullName = "JoinCode.Abstractions.Attributes.InjectAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var injectTypes = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var injectAttr = compilation.GetTypeByMetadataName(InjectAttributeFullName);
                if (injectAttr is null)
                    return ImmutableArray<InjectTypeInfo>.Empty;

                var results = new List<InjectTypeInfo>();
                VisitNamespaces(compilation.GlobalNamespace, injectAttr, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(injectTypes, static (ctx, types) =>
        {
            GenerateConstructorInjectionCode(ctx, types);
        });
    }

    private static void VisitNamespaces(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol injectAttr,
        List<InjectTypeInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, injectAttr, results);
            else if (member is INamedTypeSymbol typeSymbol)
            {
                var injections = ExtractInjections(typeSymbol, injectAttr);
                if (injections.Count > 0)
                {
                    results.Add(new InjectTypeInfo(
                        typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
                            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)),
                        injections));
                }
            }
        }
    }

    private static List<InjectField> ExtractInjections(INamedTypeSymbol typeSymbol, INamedTypeSymbol injectAttr)
    {
        var results = new List<InjectField>();

        var hasExistingCtor = typeSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Any(m => m.MethodKind == MethodKind.Constructor && !m.IsStatic && m.Parameters.Length > 0);

        if (hasExistingCtor)
            return results;

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is IFieldSymbol field && field.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, injectAttr)))
            {
                var fieldType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
                    .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
                var fieldName = field.Name;
                var paramName = fieldName.TrimStart('_');
                if (paramName.Length == 0)
                    paramName = fieldName;
                var isNullable = field.Type.NullableAnnotation == NullableAnnotation.Annotated;
                if (isNullable)
                    fieldType += "?";

                results.Add(new InjectField(fieldType, fieldName, paramName, isNullable));
            }
        }

        return results;
    }

    private static void GenerateConstructorInjectionCode(SourceProductionContext context, ImmutableArray<InjectTypeInfo> types)
    {
        var withInjections = types.Where(t => t.Injections.Count > 0).ToList();
        if (withInjections.Count == 0)
            return;

        foreach (var typeInfo in withInjections)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");

            var ns = typeInfo.ImplementationName;
            var lastDot = ns.LastIndexOf('.');
            if (lastDot < 0) continue;
            var namespacePart = ns.Substring(0, lastDot);
            if (namespacePart.StartsWith("global::"))
                namespacePart = namespacePart.Substring("global::".Length);
            var className = ns.Substring(lastDot + 1);

            sb.AppendLine();
            sb.AppendLine($"namespace {namespacePart};");
            sb.AppendLine();
            sb.AppendLine($"partial class {className}");
            sb.AppendLine("{");

            var paramList = new List<string>();
            var assignList = new List<string>();

            var ordered = typeInfo.Injections.OrderBy(i => i.IsNullable).ToList();

            foreach (var inj in ordered)
            {
                var param = $"{inj.FieldType} {inj.ParamName}";
                if (inj.IsNullable)
                    param += " = null";
                paramList.Add(param);
                assignList.Add($"        {inj.FieldName} = {inj.ParamName};");
            }

            sb.AppendLine($"    public {className}({string.Join(", ", paramList)})");
            sb.AppendLine("    {");
            foreach (var assign in assignList)
            {
                sb.AppendLine(assign);
            }
            sb.AppendLine("    }");

            sb.AppendLine("}");

            var hintName = $"GeneratedConstructorInjection_{className}.g.cs";
            context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private sealed class InjectField
    {
        public string FieldType { get; }
        public string FieldName { get; }
        public string ParamName { get; }
        public bool IsNullable { get; }

        public InjectField(string fieldType, string fieldName, string paramName, bool isNullable)
        {
            FieldType = fieldType;
            FieldName = fieldName;
            ParamName = paramName;
            IsNullable = isNullable;
        }
    }

    private sealed class InjectTypeInfo
    {
        public string ImplementationName { get; }
        public List<InjectField> Injections { get; }

        public InjectTypeInfo(string implementationName, List<InjectField> injections)
        {
            ImplementationName = implementationName;
            Injections = injections;
        }
    }
}
