global using System.Text;
global using System.Collections.Frozen;
global using System.Net;
global using System.Net.Sockets;
global using JoinCode.Abstractions.ChatCommands;
global using JoinCode.Abstractions.Onboarding;
global using JoinCode.Abstractions.State;
global using JsonElement = System.Text.Json.JsonElement;
global using ReferenceResolver = Core.Context.Resolution.ReferenceResolver;

global using Xunit;
global using Xunit.Abstractions;
global using Moq;
global using FluentAssertions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Configuration;
global using Core.DependencyInjection;

global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Diff;
global using JoinCode.Abstractions.Models.Search;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Skill;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Hooks;
global using Core.Utils;

global using Core.Context;
global using JoinCode.Abstractions.Brain.Context.Resolution;
global using Core.Configuration;
global using Core.CostTracking;
global using Core.Memdir;
global using Core.Hooks.Configuration;
global using Core.Hooks.Events;
global using Core.Hooks.Execution;
global using Core.Permission;
global using Core.Scheduling;
global using Core.Scheduling.Cron;
global using Core.Scheduling.Runtime;
global using Core.Scheduling.Tasks;
global using Core.Skills;
global using Core.Security.Constants;

global using IO.FileSystem;
global using IO.Services;
global using Services.Shell;
global using Services.Shell.Providers;

global using JoinCode.ChatCommands;

global using Integration.Tests.Capture;
global using Testing.Common;
global using Testing.Common.Services;

global using JoinCode.CodeIndex;
global using JoinCode.CodeIndex.Ast;
global using JoinCode.CodeIndex.Persistence;
global using JoinCode.Abstractions.CodeIndex;
global using Services.CodeIndex;
global using Microsoft.Data.Sqlite;
global using Infrastructure.Localization;
global using Infrastructure.Utils.Text;
global using McpToolHandlers;
global using JoinCode.Abstractions.Mcp.Registry;
global using Tools;
global using Microsoft.Extensions.Time.Testing;
global using Microsoft.Extensions.Logging.Abstractions;
global using Core.Prompts;
global using Core.Prompts.Sections;
global using JoinCode.Abstractions.Prompts;
global using Api.LLM;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using McpClient;
global using JoinCode.Abstractions.Mcp.Protocol;
global using PermissionAwareToolExecutor = McpToolRegistry.PermissionAwareToolExecutor;
global using RemoteClientManager = McpToolRegistry.RemoteClientManager;
global using Core.Summary;
global using Core.Goal;
global using Core.Planning;
global using JoinCode.Abstractions.Interfaces.Scheduling;
global using JoinCode.Abstractions.Models.Goal;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Pipeline;
global using Infrastructure.Pipeline;
global using Infrastructure.Pipeline.Middlewares;
global using Core.Context.Compact;
global using Core.Context.Compression;
global using Core.Context.Collapse;
global using Core.Agents;
global using Core.Agents.Coordinator;
global using Core.Query;
global using Core.Security.Services;
global using Services.Web;
global using SkillContext = Core.Skills.SkillContext;
global using AgentRestrictionMiddleware = Core.Permission.AgentRestrictionMiddleware;
global using Tools.Shell;
