
namespace Api.LLM;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, AllowTrailingCommas = true, ReadCommentHandling = JsonCommentHandling.Skip, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(AnthropicMessagesRequest))]
[JsonSerializable(typeof(AnthropicSystemContentBlock))]
[JsonSerializable(typeof(AnthropicMessage))]
[JsonSerializable(typeof(AnthropicTextBlock))]
[JsonSerializable(typeof(AnthropicToolUseBlock))]
[JsonSerializable(typeof(AnthropicToolResultBlock))]
[JsonSerializable(typeof(AnthropicCacheControl))]
[JsonSerializable(typeof(AnthropicToolDefinition))]
[JsonSerializable(typeof(AnthropicInputSchema))]
[JsonSerializable(typeof(AnthropicSchemaProperty))]
[JsonSerializable(typeof(AnthropicMessagesResponse))]
[JsonSerializable(typeof(AnthropicResponseContentBlock))]
[JsonSerializable(typeof(AnthropicUsage))]
[JsonSerializable(typeof(AnthropicStreamingEvent))]
[JsonSerializable(typeof(AnthropicStreamingDelta))]
[JsonSerializable(typeof(List<AnthropicSystemContentBlock>))]
[JsonSerializable(typeof(List<AnthropicMessage>))]
[JsonSerializable(typeof(List<AnthropicToolDefinition>))]
[JsonSerializable(typeof(List<AnthropicResponseContentBlock>))]
[JsonSerializable(typeof(List<AnthropicContentBlock>))]
[JsonSerializable(typeof(AnthropicToolReferenceBlock))]
[JsonSerializable(typeof(AnthropicOutputTokensDetails))]
[JsonSerializable(typeof(AnthropicContentBlockType))]
[JsonSerializable(typeof(AnthropicContentBlockType?))]
[JsonSerializable(typeof(AnthropicStreamingEventType))]
[JsonSerializable(typeof(AnthropicStreamingEventType?))]
[JsonSerializable(typeof(AnthropicDeltaType))]
[JsonSerializable(typeof(AnthropicDeltaType?))]
[JsonSerializable(typeof(AnthropicStopReason))]
[JsonSerializable(typeof(AnthropicStopReason?))]
[JsonSerializable(typeof(AnthropicContextManagement))]
[JsonSerializable(typeof(AnthropicContextEditStrategy))]
[JsonSerializable(typeof(AnthropicClearToolUsesStrategy))]
[JsonSerializable(typeof(AnthropicClearThinkingStrategy))]
[JsonSerializable(typeof(List<AnthropicContextEditStrategy>))]
internal partial class AnthropicJsonContext : JsonSerializerContext;
