global using ChatCompletionRequest = Testing.Common.MockServer.ChatCompletionRequest;
global using ChatMsg = Testing.Common.MockServer.ApiMessage;
global using ChatRequest = Testing.Common.MockServer.ChatCompletionRequest;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Hooks;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using Api.LLM;
global using Core.Hooks.Events;
global using Core.Hooks;
global using Core.Prompts.Utils;
global using JoinCode.Entry;
global using MockServer.E2E.Tests.Core;
global using MockServer.E2E.Tests.Fixtures;
global using Infrastructure.IO.Configuration;
global using MockServer.E2E.Tests.Scripts;
global using MessageRoles = Testing.Common.MockServer.MessageRoles;
global using Microsoft.Extensions.Logging.Abstractions;
global using MsgRoles = Testing.Common.MockServer.MessageRoles;
global using MockServer.E2E.Tests.Triggers;
global using System.Diagnostics;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.IO.Pipes;
global using System.Text;
global using Testing.Common;
global using Testing.Common.MockServer;
global using Testing.Common.Process;
global using Xunit.Abstractions;
