<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowPack>true</AllowPack>
    <RootNamespace>Structura</RootNamespace>
    <AssemblyName>Structura</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Remove="tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Condition="'$(UsePackedComponents)' != 'true'" Include="$(RepoRoot)foundation\AsyncLock\AsyncLock.csproj" />
    <PackageReference Condition="'$(UsePackedComponents)' == 'true'" Include="JoinCode.AsyncLock" Version="$(JccComponentPackageVersion)" />
  </ItemGroup>

</Project>
