<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowPack>true</AllowPack>
    <RootNamespace>Structura</RootNamespace>
    <AssemblyName>Structura</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Remove="tests\**\*" />
  </ItemGroup>

</Project>
