<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
        <ProjectType>test</ProjectType>
  <RootNamespace>Structura.Tests</RootNamespace>
    <AssemblyName>JoinCode.Structura.Tests</AssemblyName>
    <Description>JoinCode Structura 单元测试</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)lib/structura/Structura.csproj" />
  </ItemGroup>
</Project>
