namespace ToolPrompt.Generator;

[Generator]
public sealed class ToolPromptGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "JoinCode.Abstractions.Attributes.ToolPromptAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toolPromptInfos = context.CompilationProvider
            .SelectMany((compilation, _) =>
            {
                var types = AttributeScanner.ScanTypesWithAttribute(compilation, AttributeFullName);
                var attrSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
                if (attrSymbol is null)
                    return ImmutableArray<ToolPromptInfo>.Empty;

                var results = new List<ToolPromptInfo>();
                foreach (var typeSymbol in types)
                {
                    var attr = AttributeScanner.GetAttribute(typeSymbol, attrSymbol);
                    if (attr is null) continue;

                    var info = ExtractToolPromptInfo(typeSymbol, attr);
                    if (info is not null)
                        results.Add(info);
                }
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(toolPromptInfos, static (ctx, infos) =>
        {
            GenerateRegistration(ctx, infos);
        });
    }

    private static ToolPromptInfo? ExtractToolPromptInfo(INamedTypeSymbol typeSymbol, AttributeData attr)
    {
        var toolName = AttributeScanner.GetStringNamedArg(attr, "ToolName");
        var category = AttributeScanner.GetIntNamedArg(attr, "Category");
        var hasParameters = AttributeScanner.GetBoolNamedArg(attr, "HasParameters");

        if (string.IsNullOrEmpty(toolName))
            return null;

        var hasGetDescription = AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetDescription");
        var hasGetPrompt = AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetPrompt");
        var hasGetContent = AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetContent");
        var hasPromptField = AttributeScanner.HasStaticStringField(typeSymbol, "Prompt");
        var hasDescriptionField = AttributeScanner.HasStaticStringField(typeSymbol, "Description");

        string contentMethod;
        if (hasGetDescription)
            contentMethod = "GetDescription";
        else if (hasGetPrompt)
            contentMethod = "GetPrompt";
        else if (hasGetContent)
            contentMethod = "GetContent";
        else if (hasPromptField)
            contentMethod = "Prompt";
        else if (hasDescriptionField)
            contentMethod = "Description";
        else
            return null;

        return new ToolPromptInfo(
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString(),
            toolName!,
            category,
            hasParameters,
            contentMethod,
            hasGetDescription || hasGetContent || hasPromptField || hasDescriptionField,
            hasGetPrompt);
    }

    private static void GenerateRegistration(SourceProductionContext context, ImmutableArray<ToolPromptInfo> infos)
    {
        var orderedInfos = infos.OrderBy(i => i.ToolName).ToList();

        if (orderedInfos.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace JoinCode.Abstractions.Prompts.ToolPrompts;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 工具提示词注册表 — 由 ToolPromptGenerator 自动生成");
        sb.AppendLine("/// 根据工具名称查找详细描述，用于替换 API 请求中的短描述");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ToolPromptRegistration");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据工具名称获取详细描述，无则返回 null");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string? GetDetailedDescription(string toolName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return toolName switch");
        sb.AppendLine("        {");

        foreach (var info in orderedInfos)
        {
            if (!info.HasParameterlessAccess)
                continue;

            var fqn = info.FullyQualifiedName;
            if (info.ContentMethod == "Prompt" || info.ContentMethod == "Description")
                sb.AppendLine($"            \"{info.ToolName}\" => {fqn}.{info.ContentMethod},");
            else
                sb.AppendLine($"            \"{info.ToolName}\" => {fqn}.{info.ContentMethod}(),");
        }

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        var parameterizedInfos = orderedInfos.Where(i => i.HasParameters && i.HasGetPromptMethod).ToList();
        if (parameterizedInfos.Count > 0)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 根据工具名称获取带参数的详细描述");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static string? GetDetailedDescriptionWithParams(string toolName, params object[] args)");
            sb.AppendLine("    {");
            sb.AppendLine("        return toolName switch");
            sb.AppendLine("        {");

            foreach (var info in parameterizedInfos)
            {
                var fqn = info.FullyQualifiedName;
                sb.AppendLine($"            \"{info.ToolName}\" => {fqn}.{info.ContentMethod}(),");
            }

            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取所有已注册的工具提示词信息");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEnumerable<(string ToolName, string Category, bool HasParameters)> GetAllToolPrompts()");
        sb.AppendLine("    {");

        foreach (var info in orderedInfos)
        {
            var categoryName = ((ToolPromptCategoryValue)info.Category).ToString();
            sb.AppendLine($"        yield return (\"{info.ToolName}\", \"{categoryName}\", {info.HasParameters.ToString().ToLowerInvariant()});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ToolPromptRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private enum ToolPromptCategoryValue
    {
        Agent = 0,
        File = 1,
        Planning = 2,
        Search = 3,
        Shell = 4,
        System = 5
    }

    private sealed class ToolPromptInfo
    {
        public string FullyQualifiedName { get; }
        public string TypeName { get; }
        public string Namespace { get; }
        public string ToolName { get; }
        public int Category { get; }
        public bool HasParameters { get; }
        public string ContentMethod { get; }
        public bool HasParameterlessAccess { get; }
        public bool HasGetPromptMethod { get; }

        public ToolPromptInfo(
            string fullyQualifiedName, string typeName, string ns,
            string toolName, int category, bool hasParameters,
            string contentMethod, bool hasParameterlessAccess, bool hasGetPromptMethod)
        {
            FullyQualifiedName = fullyQualifiedName;
            TypeName = typeName;
            Namespace = ns;
            ToolName = toolName;
            Category = category;
            HasParameters = hasParameters;
            ContentMethod = contentMethod;
            HasParameterlessAccess = hasParameterlessAccess;
            HasGetPromptMethod = hasGetPromptMethod;
        }
    }
}
