global using Api;
global using JoinCode.Llm.DependencyInjection;
global using AgentInfo = Core.Agents.Coordinator.AgentInfo;
global using AgentMsg = JoinCode.Abstractions.Models.Agent.CoordinatorMessage;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Brain.Context.Hierarchy;
global using JoinCode.Abstractions.Brain.Context.Compression;
global using JoinCode.Abstractions.Brain.Context.Resolution;
global using JoinCode.Abstractions.Hooks;
global using JoinCode.Abstractions.CodeIndex;
global using CostTracker = Core.CostTracking.CostTracker;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Interfaces.Context;
global using JoinCode.Abstractions.Interfaces.Doctor;
global using JoinCode.Abstractions.Interfaces.Lsp;
global using JoinCode.Abstractions.Interfaces.Scheduling;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Execution;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Todo;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Git;
global using JoinCode.Abstractions.Models.Goal;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Shell;
global using JoinCode.Abstractions.Models.Skill;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Security.Permission;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using Core.Agents.Coordinator;
global using Core.Agents.Doctor;
global using Core.Agents.DualModel;
global using Core.Agents.Interfaces;
global using Core.Agents;
global using Core.Configuration;
global using Core.Context.Compression;
global using Core.Context.Resolution;
global using Core.Context;
global using Core.CostTracking;
global using Core.DependencyInjection;
global using Core.Query;
global using Core.Utils;

global using MessageRole = JoinCode.Abstractions.LLM.Chat.MessageRole;
global using IToolRegistry = JoinCode.Abstractions.Tools.IToolRegistry;
global using JoinCode.Abstractions.Pipeline;
global using Infrastructure.Pipeline;
global using Infrastructure.Localization;
global using IO;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using McpToolHandlers;
global using JoinCode.Abstractions.Mcp.Registry;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using McpClient;
global using McpResource = JoinCode.Abstractions.Mcp.Protocol.McpResource;
global using TaskItem = JoinCode.Abstractions.Models.Task.TaskItem;
global using TaskState = JoinCode.Abstractions.Models.Task.TaskStatus;
global using CompressionContentType = JoinCode.Abstractions.Interfaces.Context.ContentType;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Time.Testing;
global using Moq;
global using System.Runtime.CompilerServices;
global using Testing.Common;
global using Testing.Common.Services;
global using Xunit.Abstractions;
