namespace AgentPrompt.Generator;

[Generator]
internal sealed class AgentPromptGenerator : AttributeRegistrationGeneratorBase<AgentPromptGenerator.AgentPromptInfo>
{
    internal override string AttributeFullName => "JoinCode.Abstractions.Attributes.AgentPromptAttribute";

    internal override AgentPromptInfo? ExtractInfo(INamedTypeSymbol typeSymbol, AttributeData attr, Compilation compilation)
    {
        var agentType = AttributeScanner.GetStringNamedArg(attr, "AgentType");
        var displayName = AttributeScanner.GetStringNamedArg(attr, "DisplayName") ?? "";
        var description = AttributeScanner.GetStringNamedArg(attr, "Description") ?? "";

        if (string.IsNullOrEmpty(agentType))
            return null;

        var hasGetContent = AttributeScanner.HasParameterlessStaticMethod(typeSymbol, "GetContent");
        var hasPromptField = AttributeScanner.HasStaticStringField(typeSymbol, "Prompt");

        string contentMethod;
        if (hasGetContent)
            contentMethod = "GetContent";
        else if (hasPromptField)
            contentMethod = "Prompt";
        else
            return null;

        return new AgentPromptInfo(
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.Name,
            agentType!,
            displayName,
            description,
            contentMethod,
            hasPromptField);
    }

    internal override void GenerateRegistration(SourceProductionContext context, ImmutableArray<AgentPromptInfo> infos)
    {
        var orderedInfos = infos.OrderBy(i => i.AgentType).ToList();

        if (orderedInfos.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Core.Agents;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Agent 提示词注册表 — 由 AgentPromptGenerator 自动生成");
        sb.AppendLine("/// 根据 Agent 类型名称查找系统提示词");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class AgentPromptRegistration");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据 Agent 类型名称获取系统提示词，无则返回 null");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string? GetSystemPrompt(string agentType)");
        sb.AppendLine("    {");
        sb.AppendLine("        return agentType switch");
        sb.AppendLine("        {");

        foreach (var info in orderedInfos)
        {
            var fqn = info.FullyQualifiedName;
            if (info.IsFieldAccess)
                sb.AppendLine($"            \"{info.AgentType}\" => {fqn}.{info.ContentMethod},");
            else
                sb.AppendLine($"            \"{info.AgentType}\" => {fqn}.{info.ContentMethod}(),");
        }

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据 Agent 类型名称获取显示名称，无则返回 null");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string? GetDisplayName(string agentType)");
        sb.AppendLine("    {");
        sb.AppendLine("        return agentType switch");
        sb.AppendLine("        {");

        foreach (var info in orderedInfos)
        {
            sb.AppendLine($"            \"{info.AgentType}\" => \"{info.DisplayName}\",");
        }

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 根据 Agent 类型名称获取描述，无则返回 null");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string? GetDescription(string agentType)");
        sb.AppendLine("    {");
        sb.AppendLine("        return agentType switch");
        sb.AppendLine("        {");

        foreach (var info in orderedInfos)
        {
            var escaped = info.Description.Replace("\"", "\\\"");
            sb.AppendLine($"            \"{info.AgentType}\" => \"{escaped}\",");
        }

        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取所有已注册的 Agent 提示词信息");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEnumerable<(string AgentType, string DisplayName, string Description)> GetAllAgentPrompts()");
        sb.AppendLine("    {");

        foreach (var info in orderedInfos)
        {
            var escaped = info.Description.Replace("\"", "\\\"");
            sb.AppendLine($"        yield return (\"{info.AgentType}\", \"{info.DisplayName}\", \"{escaped}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("AgentPromptRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    internal sealed class AgentPromptInfo
    {
        public string FullyQualifiedName { get; }
        public string TypeName { get; }
        public string AgentType { get; }
        public string DisplayName { get; }
        public string Description { get; }
        public string ContentMethod { get; }
        public bool IsFieldAccess { get; }

        public AgentPromptInfo(
            string fullyQualifiedName, string typeName, string agentType,
            string displayName, string description, string contentMethod, bool isFieldAccess)
        {
            FullyQualifiedName = fullyQualifiedName;
            TypeName = typeName;
            AgentType = agentType;
            DisplayName = displayName;
            Description = description;
            ContentMethod = contentMethod;
            IsFieldAccess = isFieldAccess;
        }
    }
}
