global using Api.LLM;
global using Core.Utils;
global using Infrastructure.Http;
global using Infrastructure.Network.Downloader;
global using Infrastructure.Pipeline;
global using Infrastructure.Utils.IO;
global using Infrastructure.Utils.Resilience;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.Commands;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Entity;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Execution;
global using JoinCode.Abstractions.Http;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.Localization;
global using JoinCode.Abstractions.Mcp.Protocol;
global using JoinCode.Abstractions.Mcp.Registry;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Analytics;
global using JoinCode.Abstractions.Models.Interactive;
global using JoinCode.Abstractions.Models.Policy;
global using JoinCode.Abstractions.Models.Skill;
global using JoinCode.Abstractions.Models.SkillSearch;
global using JoinCode.Abstractions.Models.Telemetry;
global using JoinCode.Abstractions.Models.Vcr;
global using JoinCode.Abstractions.Models.Voice;
global using JoinCode.Abstractions.Network;
global using JoinCode.Abstractions.Pipeline;
global using JoinCode.Abstractions.Services;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.Utils.Text;
global using JoinCode.Transport;
global using McpClient;
global using McpClient.Mcpb;
global using McpClient.Models;
global using McpClient.Transports;
global using McpProtocol;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Buffers;
global using System.Collections.Frozen;
global using System.Globalization;
global using System.IO;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Sockets;
global using System.Runtime.Caching;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Channels;
global using AgentRole = JoinCode.Abstractions.Models.Agent.AgentRole;
global using AgentRoleExtensions = JoinCode.Abstractions.Models.Agent.AgentRoleExtensions;
global using ElicitAction = JoinCode.Abstractions.Mcp.Protocol.ElicitAction;
global using ElicitActionEnumConstants = JoinCode.Abstractions.Mcp.Protocol.ElicitActionEnumConstants;
global using ElicitMode = JoinCode.Abstractions.Mcp.Protocol.ElicitMode;
global using ElicitModeEnumConstants = JoinCode.Abstractions.Mcp.Protocol.ElicitModeEnumConstants;
global using ExecutionContext = JoinCode.Abstractions.Execution.ExecutionContext;
global using ExecutorVariant = JoinCode.Abstractions.Models.Agent.ExecutorVariant;
global using ExecutorVariantExtensions = JoinCode.Abstractions.Models.Agent.ExecutorVariantExtensions;
global using IElicitationHandler = JoinCode.Abstractions.Mcp.Client.IElicitationHandler;
global using IMcpAuthConfigProvider = JoinCode.Abstractions.Mcp.Client.IMcpAuthConfigProvider;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using IMcpClientFactory = JoinCode.Abstractions.Mcp.Client.IMcpClientFactory;
global using IRemoteClientManager = JoinCode.Abstractions.Mcp.Registry.IRemoteClientManager;
global using IToolHandler = JoinCode.Abstractions.Tools.IToolHandler;
global using McpAuthConfig = JoinCode.Abstractions.Mcp.Client.McpAuthConfig;
global using McpAuthType = JoinCode.Abstractions.Mcp.Client.McpAuthType;
global using McpAuthTypeEnumConstants = JoinCode.Abstractions.Mcp.Client.McpAuthTypeEnumConstants;
global using McpAuthTypeExtensions = JoinCode.Abstractions.Mcp.Client.McpAuthTypeExtensions;
global using McpClientTransportType = JoinCode.Abstractions.Mcp.Client.McpClientTransportType;
global using McpClientTransportTypeEnumConstants = JoinCode.Abstractions.Mcp.Client.McpClientTransportTypeEnumConstants;
global using McpClientTransportTypeExtensions = JoinCode.Abstractions.Mcp.Client.McpClientTransportTypeExtensions;
global using McpConnectionLostEventArgs = JoinCode.Abstractions.Mcp.Client.McpConnectionLostEventArgs;
global using McpElicitationRequestEventArgs = JoinCode.Abstractions.Mcp.Client.McpElicitationRequestEventArgs;
global using McpErrorMessages = Core.Utils.ErrorMessages;
global using McpGetPromptResult = JoinCode.Abstractions.Models.OperationResult<JoinCode.Abstractions.Mcp.Protocol.McpPromptMessage?>;
global using McpListPromptsResult = JoinCode.Abstractions.Models.OperationResult<System.Collections.Generic.IReadOnlyList<JoinCode.Abstractions.Mcp.Protocol.McpPrompt>>;
global using McpListResourcesResult = JoinCode.Abstractions.Models.OperationResult<System.Collections.Generic.IReadOnlyList<JoinCode.Abstractions.Mcp.Protocol.McpResource>>;
global using McpListToolsResult = JoinCode.Abstractions.Models.OperationResult<System.Collections.Generic.IReadOnlyList<JoinCode.Abstractions.Tools.ToolInfo>>;
global using McpNotificationReceivedEventArgs = JoinCode.Abstractions.Mcp.Client.McpNotificationReceivedEventArgs;
global using McpProgressCallback = JoinCode.Abstractions.Mcp.Client.McpProgressCallback;
global using McpProgressStatus = JoinCode.Abstractions.Mcp.Client.McpProgressStatus;
global using McpProgressStatusEnumConstants = JoinCode.Abstractions.Mcp.Client.McpProgressStatusEnumConstants;
global using McpReadResourceResult = JoinCode.Abstractions.Models.OperationResult<JoinCode.Abstractions.Mcp.Protocol.McpResourceContent?>;
global using McpServerConnectionConfig = JoinCode.Abstractions.Mcp.Client.McpServerConnectionConfig;
global using McpToolContent = JoinCode.Abstractions.Mcp.Protocol.McpToolContent;
global using McpToolProgress = JoinCode.Abstractions.Mcp.Client.McpToolProgress;
global using ServiceLifetime = JoinCode.Abstractions.Attributes.ServiceLifetime;
global using ToolContent = JoinCode.Abstractions.Tools.ToolContent;
global using ValidationResult = Structura.Primitives.ValidationResult;