global using Core.Utils;
global using FluentAssertions;
global using JoinCode.Abstractions.Configuration.Execution;
global using System.Collections.Concurrent;
global using System.IO.Pipes;
global using System.Text;
global using System.Threading.Channels;
global using Xunit;
global using Xunit.Abstractions;
