namespace AppModule.Generator;

/// <summary>
/// AppModule 源码生成器 — 扫描 [AppModule] 特性，自动生成 UseAllModules 便利方法
/// </summary>
[Generator]
public sealed class AppModuleGenerator : IIncrementalGenerator
{
    private const string AppModuleAttributeFullName = "JoinCode.App.Builder.AppModuleAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var moduleTypes = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var appModuleAttr = compilation.GetTypeByMetadataName(AppModuleAttributeFullName);
                if (appModuleAttr is null)
                    return ImmutableArray<TypeInfo>.Empty;

                var results = new List<TypeInfo>();
                VisitNamespaces(compilation.GlobalNamespace, appModuleAttr, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(moduleTypes, static (ctx, modules) =>
        {
            GenerateModuleRegistrationCode(ctx, modules);
        });
    }

    private static void VisitNamespaces(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol targetAttr,
        List<TypeInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, targetAttr, results);
            else if (member is INamedTypeSymbol typeSymbol)
            {
                var attr = typeSymbol.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, targetAttr));

                if (attr is not null)
                {
                    var order = 100;
                    var orderArg = attr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Order").Value;
                    if (orderArg.Value is int orderInt)
                        order = orderInt;

                    results.Add(new TypeInfo(
                        typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        order));
                }
            }
        }
    }

    private static void GenerateModuleRegistrationCode(SourceProductionContext context, ImmutableArray<TypeInfo> modules)
    {
        if (modules.Length == 0)
            return;

        var ordered = modules.OrderBy(m => m.Order).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using JoinCode.App.Builder;");
        sb.AppendLine();
        sb.AppendLine("namespace JoinCode.App.Builder;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 自动生成的模块注册 — 由 AppModule.Generator 扫描 [AppModule] 特性生成");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class AutoModuleRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 注册所有标记了 [AppModule] 特性的模块");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ApplicationBuilder UseAllModules(this ApplicationBuilder builder)");
        sb.AppendLine("    {");

        foreach (var module in ordered)
        {
            sb.AppendLine($"        builder.UseModule<{module.FullyQualifiedName}>();");
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedAutoModuleRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed class TypeInfo
    {
        public string FullyQualifiedName { get; }
        public int Order { get; }

        public TypeInfo(string fullyQualifiedName, int order)
        {
            FullyQualifiedName = fullyQualifiedName;
            Order = order;
        }
    }
}
