namespace Infrastructure.Localization;

public static partial class LocalizerInitializer
{
    private static void RegisterHostEntries(Dictionary<string, string> defaultEntries, Dictionary<string, string> zhEntries)
    {
        // === AdvisorCommand ===
        defaultEntries[StringKey.HostAdvisorModelLabel] = "Advisor model: {0}";
        defaultEntries[StringKey.HostAdvisorReviewMsg] = "Advisor will review the main model's work";
        defaultEntries[StringKey.HostAdvisorDisabled] = "Advisor mode: disabled";
        defaultEntries[StringKey.HostAdvisorEnableHint] = "Use /advisor <model> to enable advisor";
        defaultEntries[StringKey.HostAdvisorModeDisabled] = "Advisor mode: disabled";
        defaultEntries[StringKey.HostAdvisorModelNotSupported] = "Warning: Model '{0}' may not support advisor functionality";
        defaultEntries[StringKey.HostAdvisorSupportedModelsLabel] = "Known supported models:";
        defaultEntries[StringKey.HostAdvisorConfirmSet] = "Still set? Type /advisor <model> to confirm";

        zhEntries[StringKey.HostAdvisorModelLabel] = "顾问模型: {0}";
        zhEntries[StringKey.HostAdvisorReviewMsg] = "顾问将审查主模型的工作";
        zhEntries[StringKey.HostAdvisorDisabled] = "顾问模式：未启用";
        zhEntries[StringKey.HostAdvisorEnableHint] = "使用 /advisor <model> 启用顾问";
        zhEntries[StringKey.HostAdvisorModeDisabled] = "顾问模式：已禁用";
        zhEntries[StringKey.HostAdvisorModelNotSupported] = "警告：模型 '{0}' 可能不支持顾问功能";
        zhEntries[StringKey.HostAdvisorSupportedModelsLabel] = "已知支持模型：";
        zhEntries[StringKey.HostAdvisorConfirmSet] = "确定设置？输入 /advisor <model> 确认";

        // === AgentsCommand ===
        defaultEntries[StringKey.HostAgentsUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.HostAgentsAvailableActions] = "Available actions: list, info";
        defaultEntries[StringKey.HostAgentsProviderUnavailable] = "Agent definition provider unavailable";
        defaultEntries[StringKey.HostAgentsNoAgents] = "  No agents available";
        defaultEntries[StringKey.HostAgentsCancelled] = "Cancelled";
        defaultEntries[StringKey.HostAgentsListHeader] = "=== Agent List ===";
        defaultEntries[StringKey.HostAgentsInfoHint] = "Use /agents info <name> to view agent details";
        defaultEntries[StringKey.HostAgentsDetailHeader] = "=== Agent: {0} ===";
        defaultEntries[StringKey.HostAgentsDescriptionLabel] = "Description: {0}";
        defaultEntries[StringKey.HostAgentsWhenToUseLabel] = "When to use: {0}";
        defaultEntries[StringKey.HostAgentsBackgroundLabel] = "Background mode: {0}";
        defaultEntries[StringKey.HostAgentsModelLabel] = "Model: {0}";
        defaultEntries[StringKey.HostAgentsTemperatureLabel] = "Temperature: {0}";
        defaultEntries[StringKey.HostAgentsMaxTokensLabel] = "Max tokens: {0}";
        defaultEntries[StringKey.HostAgentsPermissionModeLabel] = "Permission mode: {0}";
        defaultEntries[StringKey.HostAgentsSourceLabel] = "Source: {0}";
        defaultEntries[StringKey.HostAgentsAllowedToolsLabel] = "Allowed tools ({0}):";
        defaultEntries[StringKey.HostAgentsDisallowedToolsLabel] = "Disallowed tools ({0}):";
        defaultEntries[StringKey.HostAgentsUsageHint] = "Usage: /agents info <agent-type>";
        defaultEntries[StringKey.HostAgentsNotFound] = "Agent not found: {0}";
        defaultEntries[StringKey.HostAgentsSkillsLabel] = "Skills:";
        defaultEntries[StringKey.HostAgentsMcServersLabel] = "MCP servers:";

        zhEntries[StringKey.HostAgentsUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.HostAgentsAvailableActions] = "可用操作：list, info";
        zhEntries[StringKey.HostAgentsProviderUnavailable] = "代理定义提供者不可用";
        zhEntries[StringKey.HostAgentsNoAgents] = "当前无可用代理";
        zhEntries[StringKey.HostAgentsCancelled] = "已取消";
        zhEntries[StringKey.HostAgentsListHeader] = "=== 代理列表 ===";
        zhEntries[StringKey.HostAgentsInfoHint] = "使用 /agents info <name> 查看代理详情";
        zhEntries[StringKey.HostAgentsDetailHeader] = "=== 代理：{0} ===";
        zhEntries[StringKey.HostAgentsDescriptionLabel] = "描述：{0}";
        zhEntries[StringKey.HostAgentsWhenToUseLabel] = "使用场景：{0}";
        zhEntries[StringKey.HostAgentsBackgroundLabel] = "后台模式：{0}";
        zhEntries[StringKey.HostAgentsModelLabel] = "模型：{0}";
        zhEntries[StringKey.HostAgentsTemperatureLabel] = "温度：{0}";
        zhEntries[StringKey.HostAgentsMaxTokensLabel] = "最大令牌：{0}";
        zhEntries[StringKey.HostAgentsPermissionModeLabel] = "权限模式：{0}";
        zhEntries[StringKey.HostAgentsSourceLabel] = "来源：{0}";
        zhEntries[StringKey.HostAgentsAllowedToolsLabel] = "允许工具 ({0}):";
        zhEntries[StringKey.HostAgentsDisallowedToolsLabel] = "禁止工具 ({0}):";
        zhEntries[StringKey.HostAgentsUsageHint] = "用法：/agents info <agent-type>";
        zhEntries[StringKey.HostAgentsNotFound] = "未找到代理：{0}";
        zhEntries[StringKey.HostAgentsSkillsLabel] = "技能：";
        zhEntries[StringKey.HostAgentsMcServersLabel] = "MCP 服务器：";

        // === AssistantCommand ===
        defaultEntries[StringKey.HostAssistantUnknownArg] = "Unknown argument: {0}";
        defaultEntries[StringKey.HostAssistantUsage] = "Usage: /assistant [on|off|status]";
        defaultEntries[StringKey.HostAssistantModeEnabled] = "Long-term assistant mode enabled";
        defaultEntries[StringKey.HostAssistantEnvVarSet] = "  Environment variable {0}=1 set (effective for current process)";
        defaultEntries[StringKey.HostAssistantPersistHint] = "For persistence, set in system environment variables";
        defaultEntries[StringKey.HostAssistantModeDisabled] = "Long-term assistant mode disabled";
        defaultEntries[StringKey.HostAssistantModeStatusHeader] = "Long-term assistant mode:";
        defaultEntries[StringKey.HostAssistantStatusEnabled] = "  Status: enabled";
        defaultEntries[StringKey.HostAssistantStatusDisabled] = "  Status: disabled";
        defaultEntries[StringKey.HostAssistantEnvStatusLabel] = "  Environment variable: {0}={1}";

        zhEntries[StringKey.HostAssistantUnknownArg] = "未知参数：{0}";
        zhEntries[StringKey.HostAssistantUsage] = "用法：/assistant [on|off|status]";
        zhEntries[StringKey.HostAssistantModeEnabled] = "长期助手模式已启用";
        zhEntries[StringKey.HostAssistantEnvVarSet] = "  环境变量 {0}=1 已设置（当前进程有效）";
        zhEntries[StringKey.HostAssistantPersistHint] = "如需持久化，请在系统环境变量中设置";
        zhEntries[StringKey.HostAssistantModeDisabled] = "长期助手模式已停用";
        zhEntries[StringKey.HostAssistantModeStatusHeader] = "长期助手模式：";
        zhEntries[StringKey.HostAssistantStatusEnabled] = "  状态：已启用";
        zhEntries[StringKey.HostAssistantStatusDisabled] = "  状态：已停用";
        zhEntries[StringKey.HostAssistantEnvStatusLabel] = "  环境变量：{0}={1}";

        // === MemoryCommand ===
        defaultEntries[StringKey.HostMemoryUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.HostMemoryAvailableActions] = "Available actions: {0}";
        defaultEntries[StringKey.HostMemoryCancelled] = "Cancelled";
        defaultEntries[StringKey.HostMemoryFilesHeader] = "── Memory Files ──";
        defaultEntries[StringKey.HostMemoryEditHint] = "Use /memory edit <number> to open editor, /memory open to open memory directory";
        defaultEntries[StringKey.HostMemoryDbHint] = "Database operations: /memory add|search|db|stats|health|cleanup";
        defaultEntries[StringKey.HostMemoryDirLabel] = "Memory directory: {0}";
        defaultEntries[StringKey.HostMemoryDirOpened] = "Opened memory directory: {0}";
        defaultEntries[StringKey.HostMemoryDirPath] = "Directory path: {0}";
        defaultEntries[StringKey.HostMemoryOpenEditorHint] = "Will open with editor {0}: {1}";
        defaultEntries[StringKey.HostMemoryOpenedInEditor] = "Opened in editor: {0}";
        defaultEntries[StringKey.HostMemoryFilePath] = "File path: {0}";
        defaultEntries[StringKey.HostMemoryAddUsage] = "Usage: /memory add <content> [--type <User|Feedback|Project|Reference>] [--tags <tag1,tag2>]";
        defaultEntries[StringKey.HostMemoryServiceUnavailable] = "Memory service unavailable";
        defaultEntries[StringKey.HostMemoryContentEmpty] = "Content cannot be empty";
        defaultEntries[StringKey.HostMemorySimilarFound] = "Found similar memory [{0}]:";
        defaultEntries[StringKey.HostMemoryScoreLabel] = "  Relevance: {0:F1}";
        defaultEntries[StringKey.HostMemoryAdded] = "Memory added [{0}]";
        defaultEntries[StringKey.HostMemoryTypeLabel] = "  Type: {0}";
        defaultEntries[StringKey.HostMemoryTagsLabel] = "  Tags: {0}";
        defaultEntries[StringKey.HostMemoryContentLabel] = "  Content: {0}";
        defaultEntries[StringKey.HostMemorySearchUsage] = "Usage: /memory search <keyword> [--type <type>]";
        defaultEntries[StringKey.HostMemorySearchHeader] = "=== Searching memory: '{0}' ===";
        defaultEntries[StringKey.HostMemoryNoResults] = "No related memories found";
        defaultEntries[StringKey.HostMemoryFoundRelated] = "Found {0} related memories";
        defaultEntries[StringKey.HostMemoryCategoryHeader] = "=== {0} memories ===";
        defaultEntries[StringKey.HostMemoryDbHeader] = "=== Database memories ===";
        defaultEntries[StringKey.HostMemoryNoMemories] = "No memories";
        defaultEntries[StringKey.HostMemoryTotal] = "Total {0} memories";
        defaultEntries[StringKey.HostMemoryStatsHeader] = "=== Memory Statistics ===";
        defaultEntries[StringKey.HostMemoryTotalCount] = "Total memories: {0}";
        defaultEntries[StringKey.HostMemoryHealthyCount] = "Healthy: {0}";
        defaultEntries[StringKey.HostMemoryNeedsAttention] = "Needs attention: {0}";
        defaultEntries[StringKey.HostMemorySuggestArchive] = "Suggest archive: {0}";
        defaultEntries[StringKey.HostMemorySuggestDelete] = "Suggest delete: {0}";
        defaultEntries[StringKey.HostMemoryAvgHealth] = "Average health score: {0:F1}";
        defaultEntries[StringKey.HostMemoryAgeDistHeader] = "Age distribution:";
        defaultEntries[StringKey.HostMemoryHealthReportHeader] = "=== Memory Health Report ===";
        defaultEntries[StringKey.HostMemoryHealthScore] = "Health: {0:F1}/100";
        defaultEntries[StringKey.HostMemorySuggestions] = "Suggestions:";
        defaultEntries[StringKey.HostMemorySuggestArchiveMsg] = "  Archive: {0} memories (>90 days unaccessed and accessed <3 times)";
        defaultEntries[StringKey.HostMemorySuggestDeleteMsg] = "  Delete: {0} memories (>180 days unaccessed and accessed <2 times)";
        defaultEntries[StringKey.HostMemoryCleanupHint] = "  Use /memory cleanup to execute cleanup";
        defaultEntries[StringKey.HostMemoryMatchReasonLabel] = "  Match reason: {0}";
        defaultEntries[StringKey.HostMemoryMostActiveHeader] = "Most active memories:";
        defaultEntries[StringKey.HostMemoryCleaning] = "Cleaning memories...";
        defaultEntries[StringKey.HostMemoryActiveInfo] = "  [{0}] Accessed {1} times, health score {2:F0}";

        defaultEntries[StringKey.HostMemoryCleanupDone] = "Cleanup complete";
        defaultEntries[StringKey.HostMemoryChecked] = "  Checked: {0}";
        defaultEntries[StringKey.HostMemoryArchived] = "  Archived: {0}";
        defaultEntries[StringKey.HostMemoryDeleted] = "  Deleted: {0}";
        defaultEntries[StringKey.HostMemoryRetained] = "  Retained: {0}";

        zhEntries[StringKey.HostMemoryUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.HostMemoryAvailableActions] = "可用操作：{0}";
        zhEntries[StringKey.HostMemoryCancelled] = "已取消";
        zhEntries[StringKey.HostMemoryFilesHeader] = "── 记忆文件 ──";
        zhEntries[StringKey.HostMemoryEditHint] = "使用 /memory edit <编号> 打开编辑, /memory open 打开记忆目录";
        zhEntries[StringKey.HostMemoryDbHint] = "数据库操作：/memory add|search|db|stats|health|cleanup";
        zhEntries[StringKey.HostMemoryDirLabel] = "记忆目录：{0}";
        zhEntries[StringKey.HostMemoryDirOpened] = "已打开记忆目录：{0}";
        zhEntries[StringKey.HostMemoryDirPath] = "目录路径：{0}";
        zhEntries[StringKey.HostMemoryOpenEditorHint] = "将使用编辑器 {0} 打开：{1}";
        zhEntries[StringKey.HostMemoryOpenedInEditor] = "已在编辑器中打开：{0}";
        zhEntries[StringKey.HostMemoryFilePath] = "文件路径：{0}";
        zhEntries[StringKey.HostMemoryAddUsage] = "用法：/memory add <内容> [--type <User|Feedback|Project|Reference>] [--tags <标签1,标签2>]";
        zhEntries[StringKey.HostMemoryServiceUnavailable] = "记忆服务不可用";
        zhEntries[StringKey.HostMemoryContentEmpty] = "内容不能为空";
        zhEntries[StringKey.HostMemorySimilarFound] = "发现相似记忆 [{0}]：";
        zhEntries[StringKey.HostMemoryScoreLabel] = "  相关度：{0:F1}";
        zhEntries[StringKey.HostMemoryAdded] = "记忆已添加 [{0}]";
        zhEntries[StringKey.HostMemoryTypeLabel] = "  类型：{0}";
        zhEntries[StringKey.HostMemoryTagsLabel] = "  标签：{0}";
        zhEntries[StringKey.HostMemoryContentLabel] = "  内容：{0}";
        zhEntries[StringKey.HostMemorySearchUsage] = "用法：/memory search <关键词> [--type <类型>]";
        zhEntries[StringKey.HostMemorySearchHeader] = "=== 搜索记忆：'{0}' ===";
        zhEntries[StringKey.HostMemoryNoResults] = "未找到相关记忆";
        zhEntries[StringKey.HostMemoryFoundRelated] = "共找到 {0} 条相关记忆";
        zhEntries[StringKey.HostMemoryCategoryHeader] = "=== {0} 类别的记忆 ===";
        zhEntries[StringKey.HostMemoryDbHeader] = "=== 数据库记忆 ===";
        zhEntries[StringKey.HostMemoryNoMemories] = "暂无记忆";
        zhEntries[StringKey.HostMemoryTotal] = "共 {0} 条记忆";
        zhEntries[StringKey.HostMemoryStatsHeader] = "=== 记忆统计 ===";
        zhEntries[StringKey.HostMemoryTotalCount] = "总记忆数：{0}";
        zhEntries[StringKey.HostMemoryHealthyCount] = "健康记忆：{0}";
        zhEntries[StringKey.HostMemoryNeedsAttention] = "需要关注：{0}";
        zhEntries[StringKey.HostMemorySuggestArchive] = "建议归档：{0}";
        zhEntries[StringKey.HostMemorySuggestDelete] = "建议删除：{0}";
        zhEntries[StringKey.HostMemoryAvgHealth] = "平均健康分：{0:F1}";
        zhEntries[StringKey.HostMemoryAgeDistHeader] = "年龄分布：";
        zhEntries[StringKey.HostMemoryHealthReportHeader] = "=== 记忆健康报告 ===";
        zhEntries[StringKey.HostMemoryHealthScore] = "健康度：{0:F1}/100";
        zhEntries[StringKey.HostMemorySuggestions] = "建议操作：";
        zhEntries[StringKey.HostMemorySuggestArchiveMsg] = "  归档：{0} 条记忆（>90天未访问且访问<3次）";
        zhEntries[StringKey.HostMemorySuggestDeleteMsg] = "  删除：{0} 条记忆（>180天未访问且访问<2次）";
        zhEntries[StringKey.HostMemoryCleanupHint] = "  使用 /memory cleanup 执行清理";
        zhEntries[StringKey.HostMemoryMatchReasonLabel] = "  匹配原因：{0}";
        zhEntries[StringKey.HostMemoryMostActiveHeader] = "最活跃记忆：";
        zhEntries[StringKey.HostMemoryCleaning] = "正在清理记忆...";
        zhEntries[StringKey.HostMemoryActiveInfo] = "  [{0}] 访问 {1} 次, 健康分 {2:F0}";

        zhEntries[StringKey.HostMemoryCleanupDone] = "清理完成";
        zhEntries[StringKey.HostMemoryChecked] = "  检查：{0}";
        zhEntries[StringKey.HostMemoryArchived] = "  归档：{0}";
        zhEntries[StringKey.HostMemoryDeleted] = "  删除：{0}";
        zhEntries[StringKey.HostMemoryRetained] = "  保留：{0}";

        // === WorkflowsCommand ===
        defaultEntries[StringKey.HostWorkflowsRunUsage] = "Usage: /workflows run <name>";
        defaultEntries[StringKey.HostWorkflowsStatusUsage] = "Usage: /workflows status <workflow_id>";
        defaultEntries[StringKey.HostWorkflowsUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.HostWorkflowsSupportedActions] = "Supported: list, run, status";
        defaultEntries[StringKey.HostWorkflowsListHeader] = "Workflow list:";
        defaultEntries[StringKey.HostWorkflowsLoadedWorkflow] = "  {0}  Loaded";
        defaultEntries[StringKey.HostWorkflowsNoLoadedWorkflows] = "  No loaded workflows";
        defaultEntries[StringKey.HostWorkflowsPluginManagerNotInitialized] = "  Plugin manager not initialized";
        defaultEntries[StringKey.HostWorkflowsRunHint] = "Use /workflows run <name> to run a workflow";
        defaultEntries[StringKey.HostWorkflowsExecutorNotInitialized] = "Workflow executor not initialized";
        defaultEntries[StringKey.HostWorkflowsPluginManagerNull] = "Plugin manager not initialized";
        defaultEntries[StringKey.HostWorkflowsPluginNotFound] = "Workflow plugin not found: {0}";
        defaultEntries[StringKey.HostWorkflowsListHint] = "Use /workflows list to see loaded workflows";
        defaultEntries[StringKey.HostWorkflowsPluginNoDefinition] = "Workflow plugin '{0}' does not provide WorkflowDefinition";
        defaultEntries[StringKey.HostWorkflowsPluginRegisterDefinition] = "Plugin needs to register WorkflowDefinition service in Load()";
        defaultEntries[StringKey.HostWorkflowsRunning] = "Running workflow: {0} ({1} steps)";
        defaultEntries[StringKey.HostWorkflowsExecutionMode] = "  Execution mode: {0}";
        defaultEntries[StringKey.HostWorkflowsExecutionComplete] = "Workflow execution complete: {0}";
        defaultEntries[StringKey.HostWorkflowsWorkflowId] = "  Workflow ID: {0}";
        defaultEntries[StringKey.HostWorkflowsDuration] = "  Duration: {0:F0}ms";
        defaultEntries[StringKey.HostWorkflowsError] = "  Error: {0}";
        defaultEntries[StringKey.HostWorkflowsStepResults] = "  Step results: {0}/{1} complete";
        defaultEntries[StringKey.HostWorkflowsStepResult] = "    {0}: {1}";
        defaultEntries[StringKey.HostWorkflowsNoResult] = "(No result)";
        defaultEntries[StringKey.HostWorkflowsExecutionCancelled] = "Workflow execution cancelled";
        defaultEntries[StringKey.HostWorkflowsStatusHeader] = "Workflow status: {0}";
        defaultEntries[StringKey.HostWorkflowsStateLabel] = "  State: {0}";
        defaultEntries[StringKey.HostWorkflowsProgress] = "  Progress: {0}/{1} steps complete";
        defaultEntries[StringKey.HostWorkflowsStepDetails] = "  Step details:";
        defaultEntries[StringKey.HostWorkflowsStepStatusDetail] = "    {0}: {1}{2}{3}";

        zhEntries[StringKey.HostWorkflowsRunUsage] = "用法：/workflows run <name>";
        zhEntries[StringKey.HostWorkflowsStatusUsage] = "用法：/workflows status <workflow_id>";
        zhEntries[StringKey.HostWorkflowsUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.HostWorkflowsSupportedActions] = "支持：list, run, status";
        zhEntries[StringKey.HostWorkflowsListHeader] = "工作流列表：";
        zhEntries[StringKey.HostWorkflowsLoadedWorkflow] = "  {0}  已加载";
        zhEntries[StringKey.HostWorkflowsNoLoadedWorkflows] = "  当前无已加载的工作流";
        zhEntries[StringKey.HostWorkflowsPluginManagerNotInitialized] = "  插件管理器未初始化";
        zhEntries[StringKey.HostWorkflowsRunHint] = "使用 /workflows run <name> 运行工作流";
        zhEntries[StringKey.HostWorkflowsExecutorNotInitialized] = "工作流执行器未初始化";
        zhEntries[StringKey.HostWorkflowsPluginManagerNull] = "插件管理器未初始化";
        zhEntries[StringKey.HostWorkflowsPluginNotFound] = "未找到工作流插件：{0}";
        zhEntries[StringKey.HostWorkflowsListHint] = "使用 /workflows list 查看已加载的工作流";
        zhEntries[StringKey.HostWorkflowsPluginNoDefinition] = "工作流插件 '{0}' 未提供 WorkflowDefinition";
        zhEntries[StringKey.HostWorkflowsPluginRegisterDefinition] = "插件需要在 Load() 中注册 WorkflowDefinition 服务";
        zhEntries[StringKey.HostWorkflowsRunning] = "正在运行工作流：{0} ({1} 个步骤)";
        zhEntries[StringKey.HostWorkflowsExecutionMode] = "  执行模式：{0}";
        zhEntries[StringKey.HostWorkflowsExecutionComplete] = "工作流执行完成：{0}";
        zhEntries[StringKey.HostWorkflowsWorkflowId] = "  工作流ID：{0}";
        zhEntries[StringKey.HostWorkflowsDuration] = "  耗时：{0:F0}ms";
        zhEntries[StringKey.HostWorkflowsError] = "  错误：{0}";
        zhEntries[StringKey.HostWorkflowsStepResults] = "  步骤结果：{0}/{1} 完成";
        zhEntries[StringKey.HostWorkflowsStepResult] = "    {0}：{1}";
        zhEntries[StringKey.HostWorkflowsNoResult] = "(无结果)";
        zhEntries[StringKey.HostWorkflowsExecutionCancelled] = "工作流执行已取消";
        zhEntries[StringKey.HostWorkflowsStatusHeader] = "工作流状态：{0}";
        zhEntries[StringKey.HostWorkflowsStateLabel] = "  状态：{0}";
        zhEntries[StringKey.HostWorkflowsProgress] = "  进度：{0}/{1} 步骤完成";
        zhEntries[StringKey.HostWorkflowsStepDetails] = "  步骤详情：";
        zhEntries[StringKey.HostWorkflowsStepStatusDetail] = "    {0}：{1}{2}{3}";

        // === KeybindingsCommand ===
        defaultEntries[StringKey.HostKeybindingsUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.HostKeybindingsSupported] = "Supported: list, edit, reset";
        defaultEntries[StringKey.HostKeybindingsLabel] = "Keybindings:";
        defaultEntries[StringKey.HostKeybindingsNoneRegistered] = "  (No registered keybindings)";
        defaultEntries[StringKey.HostKeybindingsInterrupt] = "  Ctrl+C  Interrupt current operation";
        defaultEntries[StringKey.HostKeybindingsExit] = "  Ctrl+D  Exit";
        defaultEntries[StringKey.HostKeybindingsHistory] = "  Ctrl+R  Search history";
        defaultEntries[StringKey.HostKeybindingsClear] = "  Ctrl+L  Clear screen";
        defaultEntries[StringKey.HostKeybindingsAutocomplete] = "  Tab     Autocomplete";
        defaultEntries[StringKey.HostKeybindingsSend] = "  Enter   Send message";
        defaultEntries[StringKey.HostKeybindingsCancel] = "  Esc     Cancel current input";
        defaultEntries[StringKey.HostKeybindingsEditHint] = "Use /keybindings edit to customize keybindings in editor";
        defaultEntries[StringKey.HostKeybindingsConfigCreated] = "Keybinding config file created: {0}";
        defaultEntries[StringKey.HostKeybindingsOpenEditorHint] = "Will open with editor {0}: {1}";
        defaultEntries[StringKey.HostKeybindingsOpenedInEditor] = "Opened in editor: {0}";
        defaultEntries[StringKey.HostKeybindingsConfigPath] = "Config file path: {0}";
        defaultEntries[StringKey.HostKeybindingsResetDone] = "Keybindings reset to defaults";

        zhEntries[StringKey.HostKeybindingsUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.HostKeybindingsSupported] = "支持：list, edit, reset";
        zhEntries[StringKey.HostKeybindingsLabel] = "快捷键绑定：";
        zhEntries[StringKey.HostKeybindingsNoneRegistered] = "  （无已注册的快捷键绑定）";
        zhEntries[StringKey.HostKeybindingsInterrupt] = "  Ctrl+C  中断当前操作";
        zhEntries[StringKey.HostKeybindingsExit] = "  Ctrl+D  退出";
        zhEntries[StringKey.HostKeybindingsHistory] = "  Ctrl+R  搜索历史";
        zhEntries[StringKey.HostKeybindingsClear] = "  Ctrl+L  清屏";
        zhEntries[StringKey.HostKeybindingsAutocomplete] = "  Tab     自动补全";
        zhEntries[StringKey.HostKeybindingsSend] = "  Enter   发送消息";
        zhEntries[StringKey.HostKeybindingsCancel] = "  Esc     取消当前输入";
        zhEntries[StringKey.HostKeybindingsEditHint] = "使用 /keybindings edit 在编辑器中自定义快捷键";
        zhEntries[StringKey.HostKeybindingsConfigCreated] = "已创建快捷键配置文件：{0}";
        zhEntries[StringKey.HostKeybindingsOpenEditorHint] = "将使用编辑器 {0} 打开：{1}";
        zhEntries[StringKey.HostKeybindingsOpenedInEditor] = "已在编辑器中打开：{0}";
        zhEntries[StringKey.HostKeybindingsConfigPath] = "配置文件路径：{0}";
        zhEntries[StringKey.HostKeybindingsResetDone] = "快捷键已重置为默认值";

        // === IdeCommand ===
        defaultEntries[StringKey.IdeUnknownArg] = "Unknown parameter: {0}";
        defaultEntries[StringKey.IdeUsage] = "Usage: /ide [detect|connect|disconnect|status|open]";
        defaultEntries[StringKey.IdeDetecting] = "Detecting installed IDEs...";
        defaultEntries[StringKey.IdeNoneDetected] = "No IDEs detected";
        defaultEntries[StringKey.IdeDetail] = "  {0}: {1}";
        defaultEntries[StringKey.IdeDetailPath] = "    Path: {0}";
        defaultEntries[StringKey.IdeDetectCount] = "Total IDEs detected: {0}";
        defaultEntries[StringKey.IdeConnectHint] = "Use /ide connect to connect to an IDE";
        defaultEntries[StringKey.IdeNoInstalled] = "No installed IDEs detected";
        defaultEntries[StringKey.IdeCancelled] = "Cancelled";
        defaultEntries[StringKey.IdeConnected] = "Connected to {0}";
        defaultEntries[StringKey.IdeConnectFailed] = "Failed to connect to {0}";
        defaultEntries[StringKey.IdeDetectedList] = "Detected IDEs:";
        defaultEntries[StringKey.IdeDetectedItem] = "  [{0}] {1}";
        defaultEntries[StringKey.IdeNonInteractive] = "Cannot select IDE in non-interactive mode, use: /ide connect <ide-type>";
        defaultEntries[StringKey.IdeDisconnected] = "IDE connection disconnected";
        defaultEntries[StringKey.IdeNotConnected] = "Not connected to any IDE, run /ide connect first";
        defaultEntries[StringKey.IdeOpenUsage] = "Usage: /ide open <filepath>[:<line>]";
        defaultEntries[StringKey.IdeOpened] = "Opened in {0}: {1}";
        defaultEntries[StringKey.IdeOpenFailed] = "Failed to open file: {0}";
        defaultEntries[StringKey.IdeCurrentConnection] = "Current connection: {0}";
        defaultEntries[StringKey.IdeExtensionInstalled] = "  Extension installed: {0}";
        defaultEntries[StringKey.IdeStatusConnected] = "  Status: connected";
        defaultEntries[StringKey.IdeCurrentFile] = "  Current file: {0}";
        defaultEntries[StringKey.IdeNoCurrentConnection] = "Not connected to any IDE";
        defaultEntries[StringKey.IdeInstalledList] = "Installed IDEs:";
        defaultEntries[StringKey.IdeInstalledItem] = "  {0} (extension: {1})";
        defaultEntries[StringKey.IdeNoInstalledIdes] = "No installed IDEs detected";

        zhEntries[StringKey.IdeUnknownArg] = "未知参数：{0}";
        zhEntries[StringKey.IdeUsage] = "用法：/ide [detect|connect|disconnect|status|open]";
        zhEntries[StringKey.IdeDetecting] = "正在检测已安装的 IDE...";
        zhEntries[StringKey.IdeNoneDetected] = "未检测到任何 IDE";
        zhEntries[StringKey.IdeDetail] = "  {0}：{1}";
        zhEntries[StringKey.IdeDetailPath] = "    路径：{0}";
        zhEntries[StringKey.IdeDetectCount] = "共检测到 {0} 个 IDE";
        zhEntries[StringKey.IdeConnectHint] = "使用 /ide connect 连接到 IDE";
        zhEntries[StringKey.IdeNoInstalled] = "未检测到已安装的 IDE";
        zhEntries[StringKey.IdeCancelled] = "已取消";
        zhEntries[StringKey.IdeConnected] = "已连接到 {0}";
        zhEntries[StringKey.IdeConnectFailed] = "连接 {0} 失败";
        zhEntries[StringKey.IdeDetectedList] = "检测到的 IDE：";
        zhEntries[StringKey.IdeDetectedItem] = "  [{0}] {1}";
        zhEntries[StringKey.IdeNonInteractive] = "无法在非交互模式下选择 IDE，请使用：/ide connect <ide-type>";
        zhEntries[StringKey.IdeDisconnected] = "已断开 IDE 连接";
        zhEntries[StringKey.IdeNotConnected] = "未连接 IDE，请先执行 /ide connect";
        zhEntries[StringKey.IdeOpenUsage] = "用法：/ide open <文件路径>[:<行号>]";
        zhEntries[StringKey.IdeOpened] = "已在 {0} 中打开：{1}";
        zhEntries[StringKey.IdeOpenFailed] = "打开文件失败：{0}";
        zhEntries[StringKey.IdeCurrentConnection] = "当前连接：{0}";
        zhEntries[StringKey.IdeExtensionInstalled] = "  扩展已安装：{0}";
        zhEntries[StringKey.IdeStatusConnected] = "  状态：已连接";
        zhEntries[StringKey.IdeCurrentFile] = "  当前文件：{0}";
        zhEntries[StringKey.IdeNoCurrentConnection] = "当前未连接任何 IDE";
        zhEntries[StringKey.IdeInstalledList] = "已安装的 IDE：";
        zhEntries[StringKey.IdeInstalledItem] = "  {0}（扩展：{1}）";
        zhEntries[StringKey.IdeNoInstalledIdes] = "未检测到已安装的 IDE";

        // === ResumeCommand ===
        defaultEntries[StringKey.HostResumeNotFound] = "No matching session found: '{0}'";
        defaultEntries[StringKey.HostResumeHintList] = "Hint: use /resume to view available sessions";
        defaultEntries[StringKey.HostResumeMultipleMatches] = "Multiple sessions match '{0}':";
        defaultEntries[StringKey.HostResumeMatchItem] = "  - {0} ({1})";
        defaultEntries[StringKey.HostResumeMoreMatches] = "  ... {0} more matches";
        defaultEntries[StringKey.HostResumeRefineSearch] = "Please use a more specific title or the session ID directly";
        defaultEntries[StringKey.HostResumeNoSessions] = "No resumable sessions";
        defaultEntries[StringKey.HostResumeSelectorTitle] = "Select a session to resume {0}";
        defaultEntries[StringKey.HostResumeCancelled] = "Resume cancelled";
        defaultEntries[StringKey.HostResumeNonInteractivePrompt] = "Enter number to resume (1-{0}), 'a' to toggle all projects, 'q' to cancel:";
        defaultEntries[StringKey.HostResumeNonInteractiveCancelled] = "Resume cancelled (non-interactive mode)";
        defaultEntries[StringKey.HostResumeInvalidChoice] = "Invalid choice";
        defaultEntries[StringKey.HostResumeSessionNotFound] = "Session '{0}' does not exist";
        defaultEntries[StringKey.HostResumeEntrypoint] = "[resume] Entrypoint: {0}";
        defaultEntries[StringKey.HostResumeParseError] = "Failed to parse session data";
        defaultEntries[StringKey.HostResumeNoMessages] = "Session has no message history";
        defaultEntries[StringKey.HostResumeCrossProjectNotice] = "This session is from a different project directory.";
        defaultEntries[StringKey.HostResumeCrossProjectCommandPrompt] = "To resume, run:";
        defaultEntries[StringKey.HostResumeCrossProjectCommand] = "  {0}";
        defaultEntries[StringKey.HostResumeClipboardCopied] = "(Command copied to clipboard)";
        defaultEntries[StringKey.HostResumeRestored] = "Session restored: {0}";
        defaultEntries[StringKey.HostResumeMessageCount] = "Message count: {0}";
        defaultEntries[StringKey.HostResumeRecentMessage] = "  {0}: {1}";
        defaultEntries[StringKey.HostResumeOperationCancelled] = "Session restore cancelled";

        zhEntries[StringKey.HostResumeNotFound] = "未找到匹配的会话：'{0}'";
        zhEntries[StringKey.HostResumeHintList] = "提示：使用 /resume 查看可用会话列表";
        zhEntries[StringKey.HostResumeMultipleMatches] = "多个会话匹配 '{0}'：";
        zhEntries[StringKey.HostResumeMatchItem] = "  - {0} ({1})";
        zhEntries[StringKey.HostResumeMoreMatches] = "  ... 还有 {0} 个匹配";
        zhEntries[StringKey.HostResumeRefineSearch] = "请使用更具体的标题或直接使用会话 ID";
        zhEntries[StringKey.HostResumeNoSessions] = "没有可恢复的会话";
        zhEntries[StringKey.HostResumeSelectorTitle] = "选择要恢复的会话 {0}";
        zhEntries[StringKey.HostResumeCancelled] = "已取消恢复";
        zhEntries[StringKey.HostResumeNonInteractivePrompt] = "输入编号恢复会话 (1-{0})，a 切换所有项目，q 取消:";
        zhEntries[StringKey.HostResumeNonInteractiveCancelled] = "已取消恢复（非交互模式）";
        zhEntries[StringKey.HostResumeInvalidChoice] = "无效选择";
        zhEntries[StringKey.HostResumeSessionNotFound] = "会话 '{0}' 不存在";
        zhEntries[StringKey.HostResumeEntrypoint] = "[resume] 入口: {0}";
        zhEntries[StringKey.HostResumeParseError] = "无法解析会话数据";
        zhEntries[StringKey.HostResumeNoMessages] = "会话无消息记录";
        zhEntries[StringKey.HostResumeCrossProjectNotice] = "此会话来自不同的项目目录。";
        zhEntries[StringKey.HostResumeCrossProjectCommandPrompt] = "要恢复，请运行:";
        zhEntries[StringKey.HostResumeCrossProjectCommand] = "  {0}";
        zhEntries[StringKey.HostResumeClipboardCopied] = "(命令已复制到剪贴板)";
        zhEntries[StringKey.HostResumeRestored] = "已恢复会话: {0}";
        zhEntries[StringKey.HostResumeMessageCount] = "消息数: {0}";
        zhEntries[StringKey.HostResumeRecentMessage] = "  {0}: {1}";
        zhEntries[StringKey.HostResumeOperationCancelled] = "恢复会话已取消";

        // === PermissionsCommand ===
        defaultEntries[StringKey.PermissionsUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.PermissionsAvailableActions] = "Available actions: list, add, remove, clear, workspace";
        defaultEntries[StringKey.PermissionsManagerUnavailable] = "Permission manager unavailable";
        defaultEntries[StringKey.PermissionsAddUsage] = "Usage: /permissions add <agent-pattern> <mode> [description]";
        defaultEntries[StringKey.PermissionsModeHint] = "  mode: allow | ask | deny | plan";
        defaultEntries[StringKey.PermissionsAddExample] = "  Example: /permissions add my-agent ask \"Requires confirmation\"";
        defaultEntries[StringKey.PermissionsUnknownMode] = "Unknown mode: {0}. Supported: allow, ask, deny, plan";
        defaultEntries[StringKey.PermissionsAdded] = "Permission rule added: {0} → {1}";
        defaultEntries[StringKey.PermissionsRemoveUsage] = "Usage: /permissions remove <agent-pattern>";
        defaultEntries[StringKey.PermissionsRemoved] = "Permission rule removed: {0}";
        defaultEntries[StringKey.PermissionsRuleNotFound] = "No matching permission rule found: {0}";
        defaultEntries[StringKey.PermissionsCancelled] = "Cancelled";
        defaultEntries[StringKey.PermissionsCleared] = "All permission rules cleared";
        defaultEntries[StringKey.PermissionsUnknownWorkspaceAction] = "Unknown workspace action: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceAvailableActions] = "Available actions: list, add, remove, clear";
        defaultEntries[StringKey.PermissionsWorkspaceAddUsage] = "Usage: /permissions workspace add <path>";
        defaultEntries[StringKey.PermissionsDirNotFound] = "Directory does not exist: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceServiceUnavailable] = "Workspace service unavailable";
        defaultEntries[StringKey.PermissionsWorkspaceDirAdded] = "Workspace directory added: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceDirAlreadyExists] = "Directory already in workspace: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceRemoveUsage] = "Usage: /permissions workspace remove <path>";
        defaultEntries[StringKey.PermissionsWorkspaceDirRemoved] = "Workspace directory removed: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceDirNotInWorkspace] = "Directory not in workspace: {0}";
        defaultEntries[StringKey.PermissionsWorkspaceCleared] = "All extra workspace directories cleared";

        zhEntries[StringKey.PermissionsUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.PermissionsAvailableActions] = "可用操作：list, add, remove, clear, workspace";
        zhEntries[StringKey.PermissionsManagerUnavailable] = "权限管理器不可用";
        zhEntries[StringKey.PermissionsAddUsage] = "用法：/permissions add <agent-pattern> <mode> [description]";
        zhEntries[StringKey.PermissionsModeHint] = "  模式：allow | ask | deny | plan";
        zhEntries[StringKey.PermissionsAddExample] = "  示例：/permissions add my-agent ask \"需要确认\"";
        zhEntries[StringKey.PermissionsUnknownMode] = "未知模式：{0}。支持：allow, ask, deny, plan";
        zhEntries[StringKey.PermissionsAdded] = "已添加权限规则：{0} → {1}";
        zhEntries[StringKey.PermissionsRemoveUsage] = "用法：/permissions remove <agent-pattern>";
        zhEntries[StringKey.PermissionsRemoved] = "已移除权限规则：{0}";
        zhEntries[StringKey.PermissionsRuleNotFound] = "未找到匹配的权限规则：{0}";
        zhEntries[StringKey.PermissionsCancelled] = "已取消";
        zhEntries[StringKey.PermissionsCleared] = "已清除所有权限规则";
        zhEntries[StringKey.PermissionsUnknownWorkspaceAction] = "未知工作区操作：{0}";
        zhEntries[StringKey.PermissionsWorkspaceAvailableActions] = "可用操作：list, add, remove, clear";
        zhEntries[StringKey.PermissionsWorkspaceAddUsage] = "用法：/permissions workspace add <path>";
        zhEntries[StringKey.PermissionsDirNotFound] = "目录不存在：{0}";
        zhEntries[StringKey.PermissionsWorkspaceServiceUnavailable] = "工作区服务不可用";
        zhEntries[StringKey.PermissionsWorkspaceDirAdded] = "已添加工作目录：{0}";
        zhEntries[StringKey.PermissionsWorkspaceDirAlreadyExists] = "目录已在工作区中：{0}";
        zhEntries[StringKey.PermissionsWorkspaceRemoveUsage] = "用法：/permissions workspace remove <path>";
        zhEntries[StringKey.PermissionsWorkspaceDirRemoved] = "已移除工作目录：{0}";
        zhEntries[StringKey.PermissionsWorkspaceDirNotInWorkspace] = "目录不在工作区中：{0}";
        zhEntries[StringKey.PermissionsWorkspaceCleared] = "已清除所有额外工作目录";
        // RenderRule / RenderRulesList / RenderWorkspaceContentAsync
        defaultEntries[StringKey.PermissionsNoRules] = "  No permission rules (all operations allowed by default)";
        defaultEntries[StringKey.PermissionsAddRuleHint] = "Use /permissions add <pattern> <mode> to add a rule";
        defaultEntries[StringKey.PermissionsWorkspaceCurrentDir] = " (current working directory)";
        defaultEntries[StringKey.PermissionsDirectoryNotFoundSuffix] = " (not found)";
        defaultEntries[StringKey.PermissionsTrustedDirsHeader] = "Trusted directories:";
        defaultEntries[StringKey.PermissionsAddWorkspaceHint] = "Use /permissions workspace add <path> to add a workspace directory";
        defaultEntries[StringKey.PermissionsRemoveWorkspaceHint] = "Use /permissions workspace remove <path> to remove a workspace directory";
        defaultEntries[StringKey.PermissionsRuleDescriptionLabel] = "Description: {0}";
        defaultEntries[StringKey.PermissionsRuleAllowedToolsLabel] = "Allowed tools: {0}";
        defaultEntries[StringKey.PermissionsRuleDeniedToolsLabel] = "Denied tools: {0}";
        defaultEntries[StringKey.PermissionsRuleAllowedPathsLabel] = "Allowed paths: {0}";
        defaultEntries[StringKey.PermissionsRuleDeniedPathsLabel] = "Denied paths: {0}";

        zhEntries[StringKey.PermissionsNoRules] = "当前无权限规则（默认允许所有操作）";
        zhEntries[StringKey.PermissionsAddRuleHint] = "使用 /permissions add <pattern> <mode> 添加规则";
        zhEntries[StringKey.PermissionsWorkspaceCurrentDir] = " (当前工作目录)";
        zhEntries[StringKey.PermissionsDirectoryNotFoundSuffix] = " (不存在)";
        zhEntries[StringKey.PermissionsTrustedDirsHeader] = "受信任目录:";
        zhEntries[StringKey.PermissionsAddWorkspaceHint] = "使用 /permissions workspace add <path> 添加工作目录";
        zhEntries[StringKey.PermissionsRemoveWorkspaceHint] = "使用 /permissions workspace remove <path> 移除工作目录";
        zhEntries[StringKey.PermissionsRuleDescriptionLabel] = "描述: {0}";
        zhEntries[StringKey.PermissionsRuleAllowedToolsLabel] = "允许工具: {0}";
        zhEntries[StringKey.PermissionsRuleDeniedToolsLabel] = "拒绝工具: {0}";
        zhEntries[StringKey.PermissionsRuleAllowedPathsLabel] = "允许路径: {0}";
        zhEntries[StringKey.PermissionsRuleDeniedPathsLabel] = "拒绝路径: {0}";
        defaultEntries[StringKey.PermissionsConfirmClearAll] = "Are you sure you want to clear all permission rules?";
        zhEntries[StringKey.PermissionsConfirmClearAll] = "确定要清除所有权限规则吗？";
        // Mode labels / TabPanel / RenderRule
        defaultEntries[StringKey.PermissionsModeAllowLabel] = "[Allow]";
        defaultEntries[StringKey.PermissionsModeAskLabel] = "[Ask]";
        defaultEntries[StringKey.PermissionsModeDenyLabel] = "[Deny]";
        defaultEntries[StringKey.PermissionsModePlanLabel] = "[Plan]";
        defaultEntries[StringKey.PermissionsRulePriorityLabel] = "Priority: {0}, Level: {1}";
        defaultEntries[StringKey.PermissionsTabRules] = "Rules";
        defaultEntries[StringKey.PermissionsTabWorkspace] = "Workspace";
        zhEntries[StringKey.PermissionsModeAllowLabel] = "[允许]";
        zhEntries[StringKey.PermissionsModeAskLabel] = "[询问]";
        zhEntries[StringKey.PermissionsModeDenyLabel] = "[拒绝]";
        zhEntries[StringKey.PermissionsModePlanLabel] = "[计划]";
        zhEntries[StringKey.PermissionsRulePriorityLabel] = "优先级: {0}, 级别: {1}";
        zhEntries[StringKey.PermissionsTabRules] = "规则";
        zhEntries[StringKey.PermissionsTabWorkspace] = "工作区";

        // === Non-interactive mode messages ===
        defaultEntries[StringKey.NonInteractivePermissionDenied] = "Non-interactive mode: permission denied by default.";
        zhEntries[StringKey.NonInteractivePermissionDenied] = "非交互模式：默认拒绝权限。";

        // === SandboxToggleCommand ===
        defaultEntries[StringKey.HostSandboxServiceNotInitialized] = "Sandbox service not initialized";
        defaultEntries[StringKey.HostSandboxCancelled] = "Cancelled";
        defaultEntries[StringKey.HostSandboxEnabled] = "Sandbox mode: enabled ({0})";
        defaultEntries[StringKey.HostSandboxRootPath] = "  Root path: {0}";
        defaultEntries[StringKey.HostSandboxNetworkRestricted] = "  Network restricted: {0}";
        defaultEntries[StringKey.HostSandboxDisabled] = "Sandbox mode: disabled";
        defaultEntries[StringKey.HostSandboxStatusHeader] = "Sandbox mode: {0}";
        defaultEntries[StringKey.HostSandboxTypeLabel] = "  Type: {0}";
        defaultEntries[StringKey.HostSandboxEnteredAtLabel] = "  Entered at: {0:HH:mm:ss}";
        defaultEntries[StringKey.HostSandboxRestrictedLabel] = "  Restricted: {0}";
        defaultEntries[StringKey.HostSandboxStatusPlatformSupported] = "  Platform supported: {0}";
        defaultEntries[StringKey.HostSandboxUsageEnable] = "Use /sandbox-toggle on to enable sandbox";
        defaultEntries[StringKey.HostSandboxUsageDisable] = "Use /sandbox-toggle off to disable sandbox";
        defaultEntries[StringKey.HostSandboxUsageExclude] = "Use /sandbox-toggle exclude <path> to exclude paths";
        defaultEntries[StringKey.HostSandboxExcludePathsHeader] = "Excluded paths:";
        defaultEntries[StringKey.HostSandboxExcludeNone] = "  (none)";
        defaultEntries[StringKey.HostSandboxExcludeAddUsage] = "Use /sandbox-toggle exclude <path> to add an excluded path";
        defaultEntries[StringKey.HostSandboxPathNotFound] = "Path not found: {0}";
        defaultEntries[StringKey.HostSandboxConfigUnavailable] = "Configuration service unavailable";
        defaultEntries[StringKey.HostSandboxPathExcluded] = "Path excluded: {0}";
        defaultEntries[StringKey.HostSandboxPathAlreadyExcluded] = "Path already in exclusion list: {0}";

        zhEntries[StringKey.HostSandboxServiceNotInitialized] = "沙箱服务未初始化";
        zhEntries[StringKey.HostSandboxCancelled] = "已取消";
        zhEntries[StringKey.HostSandboxEnabled] = "沙箱模式：已启用 ({0})";
        zhEntries[StringKey.HostSandboxRootPath] = "  根路径：{0}";
        zhEntries[StringKey.HostSandboxNetworkRestricted] = "  网络限制：{0}";
        zhEntries[StringKey.HostSandboxDisabled] = "沙箱模式：已禁用";
        zhEntries[StringKey.HostSandboxStatusHeader] = "沙箱模式：{0}";
        zhEntries[StringKey.HostSandboxTypeLabel] = "  类型：{0}";
        zhEntries[StringKey.HostSandboxEnteredAtLabel] = "  进入时间：{0:HH:mm:ss}";
        zhEntries[StringKey.HostSandboxRestrictedLabel] = "  受限：{0}";
        zhEntries[StringKey.HostSandboxStatusPlatformSupported] = "  平台支持：{0}";
        zhEntries[StringKey.HostSandboxUsageEnable] = "使用 /sandbox-toggle on 启用沙箱";
        zhEntries[StringKey.HostSandboxUsageDisable] = "使用 /sandbox-toggle off 禁用沙箱";
        zhEntries[StringKey.HostSandboxUsageExclude] = "使用 /sandbox-toggle exclude <path> 排除路径";
        zhEntries[StringKey.HostSandboxExcludePathsHeader] = "排除的路径：";
        zhEntries[StringKey.HostSandboxExcludeNone] = "  （无）";
        zhEntries[StringKey.HostSandboxExcludeAddUsage] = "使用 /sandbox-toggle exclude <path> 添加排除路径";
        zhEntries[StringKey.HostSandboxPathNotFound] = "路径不存在：{0}";
        zhEntries[StringKey.HostSandboxConfigUnavailable] = "配置服务不可用";
        zhEntries[StringKey.HostSandboxPathExcluded] = "已排除路径：{0}";
        zhEntries[StringKey.HostSandboxPathAlreadyExcluded] = "路径已在排除列表中：{0}";

        // === ColorCommand ===
        defaultEntries[StringKey.ColorResetDone] = "Colors reset to default";
        defaultEntries[StringKey.ColorThemeSet] = "Color theme: {0}";
        defaultEntries[StringKey.ColorTestHint] = "Use /color test to test terminal color support";
        defaultEntries[StringKey.ColorResetHint] = "Use /color reset to reset to default";
        defaultEntries[StringKey.ColorTestHeader] = "=== Terminal Color Test ===";
        defaultEntries[StringKey.ColorBasicColors] = "Basic colors:";
        defaultEntries[StringKey.ColorGreenSuccess] = "Green (success)";
        defaultEntries[StringKey.ColorRedError] = "Red (error)";
        defaultEntries[StringKey.ColorYellowWarning] = "Yellow (warning)";
        defaultEntries[StringKey.ColorGrayMuted] = "Gray (muted)";
        defaultEntries[StringKey.ColorBluePrimary] = "Blue (primary)";
        defaultEntries[StringKey.ColorCyanAccent] = "Cyan (accent)";
        defaultEntries[StringKey.ColorAnsi256] = "ANSI 256 colors:";
        defaultEntries[StringKey.ColorStyles] = "Styles:";
        defaultEntries[StringKey.ColorBold] = "Bold";
        defaultEntries[StringKey.ColorItalic] = "Italic";
        defaultEntries[StringKey.ColorUnderline] = "Underline";
        defaultEntries[StringKey.ColorAnsiSupported] = "If colors above display correctly, your terminal supports ANSI colors.";

        zhEntries[StringKey.ColorResetDone] = "颜色已重置为默认";
        zhEntries[StringKey.ColorThemeSet] = "颜色主题：{0}";
        zhEntries[StringKey.ColorTestHint] = "使用 /color test 测试终端颜色支持";
        zhEntries[StringKey.ColorResetHint] = "使用 /color reset 重置为默认";
        zhEntries[StringKey.ColorTestHeader] = "=== 终端颜色测试 ===";
        zhEntries[StringKey.ColorBasicColors] = "基础颜色：";
        zhEntries[StringKey.ColorGreenSuccess] = "绿色(成功)";
        zhEntries[StringKey.ColorRedError] = "红色(错误)";
        zhEntries[StringKey.ColorYellowWarning] = "黄色(警告)";
        zhEntries[StringKey.ColorGrayMuted] = "灰色(次要)";
        zhEntries[StringKey.ColorBluePrimary] = "蓝色(主要)";
        zhEntries[StringKey.ColorCyanAccent] = "青色(强调)";
        zhEntries[StringKey.ColorAnsi256] = "ANSI 256色：";
        zhEntries[StringKey.ColorStyles] = "样式：";
        zhEntries[StringKey.ColorBold] = "粗体";
        zhEntries[StringKey.ColorItalic] = "斜体";
        zhEntries[StringKey.ColorUnderline] = "下划线";
        zhEntries[StringKey.ColorAnsiSupported] = "如果上方颜色显示正常，说明终端支持 ANSI 颜色。";

        // === ThemeCommand ===
        defaultEntries[StringKey.ThemeSetTo] = "Theme set to {0}";
        defaultEntries[StringKey.ThemeSetUnknown] = "Unknown theme: {0}";
        defaultEntries[StringKey.ThemeCancelled] = "Cancelled";
        defaultEntries[StringKey.ThemeCurrentLabel] = "Current theme: {0}";
        defaultEntries[StringKey.ThemeAvailableHeader] = "Available themes:";
        defaultEntries[StringKey.ThemeUsageHint] = "Usage: /theme <name>";
        defaultEntries[StringKey.ThemeLabelAuto] = "Auto (match terminal)";
        defaultEntries[StringKey.ThemeLabelDark] = "Dark mode";
        defaultEntries[StringKey.ThemeLabelLight] = "Light mode";
        defaultEntries[StringKey.ThemeLabelDarkDaltonized] = "Dark mode (colorblind-friendly)";
        defaultEntries[StringKey.ThemeLabelLightDaltonized] = "Light mode (colorblind-friendly)";
        defaultEntries[StringKey.ThemeLabelDarkAnsi] = "Dark mode (ANSI colors only)";
        defaultEntries[StringKey.ThemeLabelLightAnsi] = "Light mode (ANSI colors only)";
        defaultEntries[StringKey.ThemeSelectorTitle] = "Select a theme";

        zhEntries[StringKey.ThemeSetTo] = "主题已设置为：{0}";
        zhEntries[StringKey.ThemeSetUnknown] = "未知主题：{0}";
        zhEntries[StringKey.ThemeCancelled] = "已取消";
        zhEntries[StringKey.ThemeCurrentLabel] = "当前主题：{0}";
        zhEntries[StringKey.ThemeAvailableHeader] = "可用主题：";
        zhEntries[StringKey.ThemeUsageHint] = "用法：/theme <名称>";
        zhEntries[StringKey.ThemeLabelAuto] = "自动（匹配终端）";
        zhEntries[StringKey.ThemeLabelDark] = "深色模式";
        zhEntries[StringKey.ThemeLabelLight] = "浅色模式";
        zhEntries[StringKey.ThemeLabelDarkDaltonized] = "深色模式（色盲友好）";
        zhEntries[StringKey.ThemeLabelLightDaltonized] = "浅色模式（色盲友好）";
        zhEntries[StringKey.ThemeLabelDarkAnsi] = "深色模式（仅 ANSI 颜色）";
        zhEntries[StringKey.ThemeLabelLightAnsi] = "浅色模式（仅 ANSI 颜色）";
        zhEntries[StringKey.ThemeSelectorTitle] = "选择主题";

        // === BridgeCommand ===
        defaultEntries[StringKey.HostBridgeUnknownAction] = "Unknown action: {0}";
        defaultEntries[StringKey.HostBridgeAvailableActions] = "Available actions: qr, sessions, status, connect, disconnect";
        defaultEntries[StringKey.HostBridgeServiceProviderUnavailable] = "Service provider unavailable, cannot generate QR code";
        defaultEntries[StringKey.HostBridgeUIServiceNotRegistered] = "Bridge UI service not registered, please ensure Bridge feature is enabled";
        defaultEntries[StringKey.HostBridgeScanQrHint] = "Scan the QR code above with mobile to connect a Bridge session";
        defaultEntries[StringKey.HostBridgeSessionsHeader] = "=== Bridge Active Sessions ===";
        defaultEntries[StringKey.HostBridgeNoActiveSessions] = "  No active sessions";
        defaultEntries[StringKey.HostBridgeSessionId] = "  {0}";
        defaultEntries[StringKey.HostBridgeSessionStatus] = "    Status: {0}";
        defaultEntries[StringKey.HostBridgeSessionClient] = "    Client: {0}";
        defaultEntries[StringKey.HostBridgeSessionConnectedAt] = "    Connected: {0}";
        defaultEntries[StringKey.HostBridgeStatusHeader] = "=== Bridge Status ===";
        defaultEntries[StringKey.HostBridgeServiceProviderNotAvailable] = "Service provider unavailable";
        defaultEntries[StringKey.HostBridgeServerRegistered] = "Server: registered";
        defaultEntries[StringKey.HostBridgeServerNotRegistered] = "Server: not registered";
        defaultEntries[StringKey.HostBridgeClientRegistered] = "Client: registered";
        defaultEntries[StringKey.HostBridgeClientNotRegistered] = "Client: not registered";
        defaultEntries[StringKey.HostBridgeUIServiceRegistered] = "UI Service: registered";
        defaultEntries[StringKey.HostBridgeUIServiceNotRegistered2] = "UI Service: not registered";
        defaultEntries[StringKey.HostBridgeClientNotConfigured] = "Bridge client not configured";
        defaultEntries[StringKey.HostBridgeAlreadyConnected] = "Bridge already connected";
        defaultEntries[StringKey.HostBridgeStartingClient] = "Starting Bridge client...";
        defaultEntries[StringKey.HostBridgeClientStarted] = "Bridge client started";
        defaultEntries[StringKey.HostBridgeNotConnected] = "Bridge not connected";
        defaultEntries[StringKey.HostBridgeDisconnected] = "Bridge connection disconnected";

        zhEntries[StringKey.HostBridgeUnknownAction] = "未知操作：{0}";
        zhEntries[StringKey.HostBridgeAvailableActions] = "可用操作：qr, sessions, status, connect, disconnect";
        zhEntries[StringKey.HostBridgeServiceProviderUnavailable] = "服务提供者不可用，无法生成 QR 码";
        zhEntries[StringKey.HostBridgeUIServiceNotRegistered] = "Bridge UI 服务未注册，请确认 Bridge 功能已启用";
        zhEntries[StringKey.HostBridgeScanQrHint] = "使用移动端扫描上方 QR 码以连接 Bridge 会话";
        zhEntries[StringKey.HostBridgeSessionsHeader] = "=== Bridge 活跃会话 ===";
        zhEntries[StringKey.HostBridgeNoActiveSessions] = "当前无活跃会话";
        zhEntries[StringKey.HostBridgeSessionId] = "  {0}";
        zhEntries[StringKey.HostBridgeSessionStatus] = "    状态：{0}";
        zhEntries[StringKey.HostBridgeSessionClient] = "    客户端：{0}";
        zhEntries[StringKey.HostBridgeSessionConnectedAt] = "    连接时间：{0}";
        zhEntries[StringKey.HostBridgeStatusHeader] = "=== Bridge 状态 ===";
        zhEntries[StringKey.HostBridgeServiceProviderNotAvailable] = "服务提供者不可用";
        zhEntries[StringKey.HostBridgeServerRegistered] = "服务端：已注册";
        zhEntries[StringKey.HostBridgeServerNotRegistered] = "服务端：未注册";
        zhEntries[StringKey.HostBridgeClientRegistered] = "客户端：已注册";
        zhEntries[StringKey.HostBridgeClientNotRegistered] = "客户端：未注册";
        zhEntries[StringKey.HostBridgeUIServiceRegistered] = "UI 服务：已注册";
        zhEntries[StringKey.HostBridgeUIServiceNotRegistered2] = "UI 服务：未注册";
        zhEntries[StringKey.HostBridgeClientNotConfigured] = "Bridge 客户端未配置";
        zhEntries[StringKey.HostBridgeAlreadyConnected] = "Bridge 已连接";
        zhEntries[StringKey.HostBridgeStartingClient] = "正在启动 Bridge 客户端...";
        zhEntries[StringKey.HostBridgeClientStarted] = "Bridge 客户端已启动";
        zhEntries[StringKey.HostBridgeNotConnected] = "Bridge 未连接";
        zhEntries[StringKey.HostBridgeDisconnected] = "已断开 Bridge 连接";

        // === Onboarding ===
        defaultEntries[StringKey.OnboardingWelcomeTitle] = "Welcome to JoinCode";
        defaultEntries[StringKey.OnboardingWelcomeSubtitle] = "Your AI-powered terminal assistant.";
        defaultEntries[StringKey.OnboardingWelcomeHint] = "Press Enter to continue";
        defaultEntries[StringKey.OnboardingApiKeyTitle] = "API Key Setup";
        defaultEntries[StringKey.OnboardingApiKeyInstruction] = "Set your API key via environment variable:";
        defaultEntries[StringKey.OnboardingApiKeyExample] = "export JCC_API_KEY=your-key";
        defaultEntries[StringKey.OnboardingApiKeyHint] = "Press Enter to continue";
        defaultEntries[StringKey.OnboardingSecurityTitle] = "Security Notice";
        defaultEntries[StringKey.OnboardingSecurityWarning1] = "AI may make mistakes. Always review changes.";
        defaultEntries[StringKey.OnboardingSecurityWarning2] = "Be aware of prompt injection risks.";
        defaultEntries[StringKey.OnboardingSecurityHint] = "Press Enter to continue";
        defaultEntries[StringKey.OnboardingTerminalTitle] = "Terminal Setup";
        defaultEntries[StringKey.OnboardingTerminalOptionRecommended] = "Use recommended settings";
        defaultEntries[StringKey.OnboardingTerminalOptionSkip] = "Skip";
        defaultEntries[StringKey.OnboardingTerminalHint] = "Enter=Select  Esc=Skip";
        defaultEntries[StringKey.OnboardingCompleteTitle] = "Ready!";
        defaultEntries[StringKey.OnboardingCompleteMessage] = "Setup complete. Type your message to start.";
        defaultEntries[StringKey.OnboardingCompleteHint] = "Press Enter to begin";
        defaultEntries[StringKey.OnboardingStepFormat] = "Step {0}/{1}";

        zhEntries[StringKey.OnboardingWelcomeTitle] = "欢迎使用 JoinCode";
        zhEntries[StringKey.OnboardingWelcomeSubtitle] = "您的 AI 终端助手";
        zhEntries[StringKey.OnboardingWelcomeHint] = "按 Enter 继续";
        zhEntries[StringKey.OnboardingApiKeyTitle] = "API 密钥设置";
        zhEntries[StringKey.OnboardingApiKeyInstruction] = "通过环境变量设置 API 密钥：";
        zhEntries[StringKey.OnboardingApiKeyExample] = "export JCC_API_KEY=your-key";
        zhEntries[StringKey.OnboardingApiKeyHint] = "按 Enter 继续";
        zhEntries[StringKey.OnboardingSecurityTitle] = "安全提示";
        zhEntries[StringKey.OnboardingSecurityWarning1] = "AI 可能会犯错，请务必审查更改";
        zhEntries[StringKey.OnboardingSecurityWarning2] = "注意提示注入风险";
        zhEntries[StringKey.OnboardingSecurityHint] = "按 Enter 继续";
        zhEntries[StringKey.OnboardingTerminalTitle] = "终端设置";
        zhEntries[StringKey.OnboardingTerminalOptionRecommended] = "使用推荐设置";
        zhEntries[StringKey.OnboardingTerminalOptionSkip] = "跳过";
        zhEntries[StringKey.OnboardingTerminalHint] = "Enter=选择  Esc=跳过";
        zhEntries[StringKey.OnboardingCompleteTitle] = "准备就绪！";
        zhEntries[StringKey.OnboardingCompleteMessage] = "设置完成，输入消息即可开始";
        zhEntries[StringKey.OnboardingCompleteHint] = "按 Enter 开始";
        zhEntries[StringKey.OnboardingStepFormat] = "步骤 {0}/{1}";
    }
}
