
namespace EnumMetadata.Generator;

/// <summary>
/// 枚举元数据源码生成器 — 扫描 [EnumValue] 特性，自动生成 ToValue/FromValue 映射代码
/// </summary>
[Generator]
public sealed class EnumMetadataGenerator : IIncrementalGenerator
{
    private const string EnumValueAttributeFullName = "JoinCode.Abstractions.Attributes.EnumValueAttribute";
    private const string AliasValueAttributeFullName = "JoinCode.Abstractions.Attributes.AliasValueAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumInfos = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var enumValueAttr = compilation.GetTypeByMetadataName(EnumValueAttributeFullName);
                var aliasValueAttr = compilation.GetTypeByMetadataName(AliasValueAttributeFullName);
                if (enumValueAttr is null)
                    return ImmutableArray<EnumInfo>.Empty;

                var results = new List<EnumInfo>();
                VisitNamespaces(compilation.GlobalNamespace, compilation.Assembly, enumValueAttr, aliasValueAttr, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(enumInfos, static (ctx, enums) =>
        {
            foreach (var enumInfo in enums)
            {
                GenerateExtensionClass(ctx, enumInfo);
            }
        });
    }

    private static void VisitNamespaces(
        INamespaceSymbol namespaceSymbol,
        IAssemblySymbol currentAssembly,
        INamedTypeSymbol enumValueAttr,
        INamedTypeSymbol? aliasValueAttr,
        List<EnumInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, currentAssembly, enumValueAttr, aliasValueAttr, results);
            else if (member is INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType
                     && SymbolEqualityComparer.Default.Equals(enumType.ContainingAssembly, currentAssembly))
            {
                var members = new List<EnumMemberInfo>();
                foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
                {
                    var attr = field.GetAttributes()
                        .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, enumValueAttr));
                    if (attr is not null)
                    {
                        var value = attr.ConstructorArguments.ElementAtOrDefault(0).Value as string ?? field.Name;

                        var aliases = ImmutableArray<string>.Empty;
                        if (aliasValueAttr is not null)
                        {
                            var aliasAttrs = field.GetAttributes()
                                .Where(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, aliasValueAttr))
                                .Select(a => a.ConstructorArguments.ElementAtOrDefault(0).Value as string)
                                .Where(a => a is not null)
                                .Cast<string>()
                                .ToImmutableArray();
                            aliases = aliasAttrs;
                        }

                        members.Add(new EnumMemberInfo(field.Name, value, aliases));
                    }
                }

                if (members.Count > 0)
                {
                    results.Add(new EnumInfo(
                        enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        enumType.Name,
                        enumType.ContainingNamespace.ToDisplayString(),
                        members.ToImmutableArray()));
                }
            }
        }
    }

    private static void GenerateExtensionClass(SourceProductionContext context, EnumInfo enumInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {enumInfo.Namespace};");
        sb.AppendLine();

        // 生成 const string 常量类 — 替代手写的 XxxConstants 类
        sb.AppendLine($"public static class {enumInfo.Name}Constants");
        sb.AppendLine("{");
        foreach (var member in enumInfo.Members)
        {
            sb.AppendLine($"    public const string {member.Name} = \"{EscapeString(member.Value)}\";");
            foreach (var alias in member.Aliases)
            {
                sb.AppendLine($"    public const string {member.Name}Alias_{EscapeIdentifier(alias)} = \"{EscapeString(alias)}\";");
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // 生成扩展方法类
        sb.AppendLine($"public static class {enumInfo.Name}Extensions");
        sb.AppendLine("{");

        // 正向映射: Enum -> string
        sb.AppendLine($"    private static readonly FrozenDictionary<{enumInfo.FullyQualifiedName}, string> __valueMap = new Dictionary<{enumInfo.FullyQualifiedName}, string>");
        sb.AppendLine("    {");
        foreach (var member in enumInfo.Members)
        {
            sb.AppendLine($"        [{enumInfo.FullyQualifiedName}.{member.Name}] = \"{EscapeString(member.Value)}\",");
        }
        sb.AppendLine("    }.ToFrozenDictionary();");
        sb.AppendLine();

        // 反向映射: string -> Enum（含别名）
        sb.AppendLine($"    private static readonly FrozenDictionary<string, {enumInfo.FullyQualifiedName}> __reverseMap = new Dictionary<string, {enumInfo.FullyQualifiedName}>");
        sb.AppendLine("    {");
        foreach (var member in enumInfo.Members)
        {
            sb.AppendLine($"        [\"{EscapeString(member.Value)}\"] = {enumInfo.FullyQualifiedName}.{member.Name},");
            foreach (var alias in member.Aliases)
            {
                sb.AppendLine($"        [\"{EscapeString(alias)}\"] = {enumInfo.FullyQualifiedName}.{member.Name},");
            }
        }
        sb.AppendLine("    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();

        // ToValue 扩展方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取枚举成员的字符串值");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static string ToValue(this {enumInfo.FullyQualifiedName} value)");
        sb.AppendLine($"        => __valueMap.GetValueOrDefault(value, value.ToString().ToLowerInvariant());");
        sb.AppendLine();

        // FromValue 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 从字符串值解析枚举成员");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {enumInfo.FullyQualifiedName}? FromValue(string? value)");
        sb.AppendLine($"        => value is not null && __reverseMap.TryGetValue(value, out var result) ? result : null;");

        // IsDefined 方法
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 判断枚举值是否为已定义的成员");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static bool IsDefined({enumInfo.FullyQualifiedName} value)");
        sb.AppendLine("        => __valueMap.ContainsKey(value);");

        sb.AppendLine("}");

        context.AddSource($"{enumInfo.Name}Extensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeIdentifier(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var c in s)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    private sealed class EnumInfo
    {
        public string FullyQualifiedName { get; }
        public string Name { get; }
        public string Namespace { get; }
        public ImmutableArray<EnumMemberInfo> Members { get; }

        public EnumInfo(string fullyQualifiedName, string name, string ns, ImmutableArray<EnumMemberInfo> members)
        {
            FullyQualifiedName = fullyQualifiedName;
            Name = name;
            Namespace = ns;
            Members = members;
        }
    }

    private sealed class EnumMemberInfo
    {
        public string Name { get; }
        public string Value { get; }
        public ImmutableArray<string> Aliases { get; }

        public EnumMemberInfo(string name, string value, ImmutableArray<string> aliases)
        {
            Name = name;
            Value = value;
            Aliases = aliases;
        }
    }
}
