namespace Services.Lsp;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, WriteIndented = true, AllowTrailingCommas = true, ReadCommentHandling = JsonCommentHandling.Skip, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(List<LspServerConfigEntry>))]
[JsonSerializable(typeof(LspServerConfigEntry))]
[JsonSerializable(typeof(List<LspLocation>))]
[JsonSerializable(typeof(LspLocation))]
[JsonSerializable(typeof(LspHoverResult))]
[JsonSerializable(typeof(List<LspCompletionItem>))]
[JsonSerializable(typeof(LspCompletionItem))]
[JsonSerializable(typeof(List<LspDocumentSymbol>))]
[JsonSerializable(typeof(LspDocumentSymbol))]
[JsonSerializable(typeof(List<LspSymbolInformation>))]
[JsonSerializable(typeof(LspSymbolInformation))]
[JsonSerializable(typeof(LspPosition))]
[JsonSerializable(typeof(LspRange))]
[JsonSerializable(typeof(LspJsonRpcRequest))]
[JsonSerializable(typeof(LspJsonRpcNotification))]
[JsonSerializable(typeof(LspInitializeParams))]
[JsonSerializable(typeof(LspTextDocumentIdentifier))]
[JsonSerializable(typeof(LspTextDocumentPositionParams))]
[JsonSerializable(typeof(LspReferenceParams))]
[JsonSerializable(typeof(LspReferenceContext))]
[JsonSerializable(typeof(LspDidOpenTextDocumentParams))]
[JsonSerializable(typeof(LspTextDocumentItem))]
[JsonSerializable(typeof(LspWorkspaceSymbolParams))]
[JsonSerializable(typeof(LspCallHierarchyItem))]
[JsonSerializable(typeof(List<LspCallHierarchyItem>))]
[JsonSerializable(typeof(LspCallHierarchyItemParam))]
[JsonSerializable(typeof(LspCallHierarchyIncomingCall))]
[JsonSerializable(typeof(List<LspCallHierarchyIncomingCall>))]
[JsonSerializable(typeof(LspCallHierarchyOutgoingCall))]
[JsonSerializable(typeof(List<LspCallHierarchyOutgoingCall>))]
[JsonSerializable(typeof(LspJsonRpcError))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(List<Dictionary<string, JsonElement>>))]
public partial class LspJsonContext : JsonSerializerContext;
