global using JoinCode.Abstractions.Localization;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.Hooks;
global using JoinCode.Abstractions.CodeIndex;
global using JoinCode.Abstractions.Commands;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Interfaces.Context;
global using JoinCode.Abstractions.Interfaces.Lsp;
global using JoinCode.Abstractions.Interfaces.Scheduling;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.LLM.Execution;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Git;
global using JoinCode.Abstractions.Models.Goal;
global using JoinCode.Abstractions.Models.Interactive;
global using JoinCode.Abstractions.Models.Plan;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Models.Todo;
global using TaskStatus = JoinCode.Abstractions.Models.Task.TaskStatus;
global using JoinCode.Abstractions.Models.Telemetry;
global using JoinCode.Abstractions.Prompts;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Security.Permission;
global using JoinCode.Abstractions.Security.Shell;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.Utils.Text;
global using ContractAgentMessage = JoinCode.Abstractions.Models.Agent.AgentMessage;
global using CoordinatorAgentMessage = JoinCode.Abstractions.Models.Agent.CoordinatorMessage;
global using ContractsErrorMessages = JoinCode.Abstractions.Utils.ErrorMessages;
global using AgentStateRecord = JoinCode.Abstractions.State.AgentState;
global using CompressionContentType = JoinCode.Abstractions.Interfaces.Context.ContentType;
global using AsyncFileLock;
global using JoinCode.Abstractions.Brain.Context.Hierarchy;
global using JoinCode.Abstractions.Brain.Context.Compression;
global using JoinCode.Abstractions.Brain.Context.Resolution;
global using JoinCode.Abstractions.Brain.Planning;
global using Core.Agents;
global using Core.Agents.Coordinator;
global using Core.Agents.Interfaces;
global using Core.Agents.ToolHandlers;
global using Core.Agents.Worktree;
global using Core.Configuration;
global using Core.DependencyInjection;
global using Core.Utils;
global using JoinCode.Abstractions.Hooks.Session;
global using Infrastructure.Utils.IO;
global using Infrastructure.Utils.Text;
global using Infrastructure.Utils.System;
global using IO;
global using IO.Services;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using IMcpClientFactory = JoinCode.Abstractions.Mcp.Client.IMcpClientFactory;
global using McpServerConnectionConfig = JoinCode.Abstractions.Mcp.Client.McpServerConnectionConfig;
global using McpClientTransportType = JoinCode.Abstractions.Mcp.Client.McpClientTransportType;
global using McpAuthConfig = JoinCode.Abstractions.Mcp.Client.McpAuthConfig;
global using McpAuthType = JoinCode.Abstractions.Mcp.Client.McpAuthType;
global using McpClientTransportTypeExtensions = JoinCode.Abstractions.Mcp.Client.McpClientTransportTypeExtensions;
global using McpAuthTypeExtensions = JoinCode.Abstractions.Mcp.Client.McpAuthTypeExtensions;
global using IRemoteClientManager = JoinCode.Abstractions.Mcp.Registry.IRemoteClientManager;
global using IMcpAuthConfigProvider = JoinCode.Abstractions.Mcp.Client.IMcpAuthConfigProvider;
global using JoinCode.Abstractions.Mcp.Registry;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.Collections.Frozen;
global using System.ComponentModel.DataAnnotations;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading.Channels;
global using System.Runtime.CompilerServices;
global using JoinCode.Abstractions.Models.Features;
global using JoinCode.Abstractions.Pipeline;
global using Infrastructure.Pipeline;
global using TuiSymbols = JoinCode.Abstractions.Utils.TuiSymbols;
