global using Core.Utils;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.Http;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Transport;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Transport.DependencyInjection;
global using JoinCode.Abstractions.Entity;
global using Microsoft.Extensions.Logging;
