<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Vision.Tests</RootNamespace>
    <AssemblyName>JoinCode.Vision.Tests</AssemblyName>
    <Description>JoinCode.Vision 单元测试</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)foundation\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="$(RepoRoot)services\Vision\src\Vision.csproj" />
    <ProjectReference Include="$(RepoRoot)tests\Unit\Testing.Common\Testing.Common.csproj" />
  </ItemGroup>

</Project>
