<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectType>test</ProjectType>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAotCompatible>true</IsAotCompatible>
    <ExcludeTestSdk>true</ExcludeTestSdk>
    <NoWarn>$(NoWarn);JCC1005;JCC9001;IDE0007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PithosDB" Version="1.6.0" />
  </ItemGroup>

</Project>
