global using JoinCode.Transport;
global using JoinCode.Abstractions.Transport;
global using JoinCode.Transport.Bridge;
global using JoinCode.Browser.DependencyInjection;
global using JoinCode.Cli.Display;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Hooks;
global using JoinCode.Abstractions.Localization;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.ChatCommands;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Interfaces.Scheduling;
global using JoinCode.Abstractions.Interfaces.Security;
global using JoinCode.Abstractions.Insights;
global using JoinCode.Abstractions.UI;
global using JoinCode.Abstractions.Onboarding;
global using CompactDirection = JoinCode.Abstractions.LLM.Chat.CompactDirection;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.LLM.Execution;
global using MessageRole = JoinCode.Abstractions.LLM.Chat.MessageRole;
global using MessageRoleConstants = JoinCode.Abstractions.LLM.Chat.MessageRoleConstants;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Diff;
global using JoinCode.Abstractions.Models.Git;
global using JoinCode.Abstractions.Models.Goal;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Models.Todo;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Security.Permission;
global using JoinCode.Abstractions.Security.Shell;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.Utils.Text;
global using ChatStreamEvent = JoinCode.Abstractions.LLM.Chat.ChatStreamEvent;
global using ChatStreamEventType = JoinCode.Abstractions.LLM.Chat.ChatStreamEventType;
global using Core.Bridge;
global using Core.Configuration;
global using Core.Configuration.Providers;
global using Core.Context;
global using Core.CostTracking;
global using Core.DependencyInjection;
global using Core.Goal;
global using JoinCode.Clock.DependencyInjection;
global using Core.Hooks.Configuration;
global using Core.Hooks.Events;
global using Core.Hooks.Lifecycle;
global using Core.Memdir;
global using Core.Plugins;
global using Core.Scheduling.Cron;
global using Core.Scheduling.Tasks;
global using Core.Security.Services;
global using Core.Telemetry;
global using JoinCode.Abstractions.Models.Telemetry;
global using Core.Utils;
global using Infrastructure.Utils.IO;
global using Infrastructure.Utils.Text;
global using Infrastructure.Time;
global using IO.FileSystem;
global using Services.Api;
global using Services.Shell;
global using JoinCode.ChatCommands;
global using JoinCode.Cli;
global using JoinCode.CliCommands;
global using JoinCode.Services;
global using JoinCode.Adapters;

global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using JoinCode.Abstractions.Mcp.Registry;
global using McpClient;
global using ToolCacheManager = McpToolRegistry.ToolCacheManager;
global using RemoteClientManager = McpToolRegistry.RemoteClientManager;
global using JoinCode.Abstractions.Prompts.ToolPrompts;
global using IToolRegistry = JoinCode.Abstractions.Tools.IToolRegistry;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using Services.OAuth;
global using System.Collections.Frozen;
global using System.CommandLine;
global using System.IO.Pipes;
global using System.Net.Http.Json;
global using System.Net;
global using System.Security.Cryptography;
global using System.Text.Json.Serialization.Metadata;
global using System.Text.Json.Serialization;
global using System.Text;
global using System.Threading.Channels;
global using Tools;
global using TranscriptEntry = JoinCode.Abstractions.LLM.Chat.TranscriptEntry;
global using RewindResult = JoinCode.Abstractions.LLM.Chat.RewindResult;

global using JoinCode.Dream;
global using Plugins.Browser;

// ApplicationBuilder 模块化
global using JoinCode.App.Builder;
global using JoinCode.Pipe;

// 管道中间件
global using JoinCode.Abstractions.Pipeline;
global using Infrastructure.Pipeline;
global using Infrastructure.Pipeline.Middlewares;

// CLI TerminalHelper — 替代 JoinCode.Console.Terminal.TerminalHelper（已移至 .x/）
global using TerminalHelper = JoinCode.Cli.TerminalHelper;

// PipelineComposition 需要的命名空间
global using Core.Agents;
global using Core.Agents.Coordinator;
global using Core.Context.Compact;
global using Core.Permission;
global using Core.Query;
global using Core.Skills;
global using Services.Web;
global using Tools.Shell;
global using SkillContext = Core.Skills.SkillContext;
global using JoinCode.App.Middlewares;
global using AgentRestrictionMiddleware = Core.Permission.AgentRestrictionMiddleware;
global using QueryTokenBudgetMiddleware = Core.Query.TokenBudgetMiddleware;
global using ChatTokenBudgetMiddleware = JoinCode.App.Middlewares.TokenBudgetMiddleware;
