
namespace Core.Configuration;

[JsonSourceGenerationOptions(WriteIndented = false, ReadCommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(SettingsJson))]
[JsonSerializable(typeof(CurrentSettings))]
[JsonSerializable(typeof(PermissionsSettings))]
[JsonSerializable(typeof(HookSettings))]
[JsonSerializable(typeof(McpServerSettings))]
[JsonSerializable(typeof(SandboxSettings))]
[JsonSerializable(typeof(PluginSettings))]
[JsonSerializable(typeof(WorktreeSettings))]
[JsonSerializable(typeof(StatusLineSettings))]
[JsonSerializable(typeof(ProfileSettings))]
[JsonSerializable(typeof(ModelItemConfig))]
[JsonSerializable(typeof(ModelCapabilitiesConfig))]
[JsonSerializable(typeof(ModelPricingConfig))]
public partial class ConfigJsonContext : JsonSerializerContext;

[JsonSourceGenerationOptions(WriteIndented = true, ReadCommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(SettingsJson))]
[JsonSerializable(typeof(CurrentSettings))]
[JsonSerializable(typeof(PermissionsSettings))]
[JsonSerializable(typeof(HookSettings))]
[JsonSerializable(typeof(McpServerSettings))]
[JsonSerializable(typeof(SandboxSettings))]
[JsonSerializable(typeof(PluginSettings))]
[JsonSerializable(typeof(WorktreeSettings))]
[JsonSerializable(typeof(StatusLineSettings))]
[JsonSerializable(typeof(ProfileSettings))]
[JsonSerializable(typeof(ModelItemConfig))]
[JsonSerializable(typeof(ModelCapabilitiesConfig))]
[JsonSerializable(typeof(ModelPricingConfig))]
public partial class ConfigIndentedJsonContext : JsonSerializerContext;
