global using Core.Bridge;
global using Core.Bridge.Gate;
global using Core.Bridge.Handlers;
global using Core.Bridge.Models;
global using Infrastructure.Pipeline;
global using Infrastructure.Time;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Security.Permission;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Transport;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Transport;
global using JoinCode.Transport.Bridge;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Time.Testing;
global using Moq;
global using System.Net.WebSockets;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using Testing.Common;
global using Testing.Common.Services;
global using Xunit.Abstractions;
global using BridgeNdjsonActivity = JoinCode.Transport.Bridge.NdjsonActivity;
// Transport 迁移类型别名
global using BridgeNdjsonActivityType = JoinCode.Transport.Bridge.NdjsonActivityType;
global using BridgeNdjsonParser = JoinCode.Transport.Bridge.NdjsonParser;
global using BridgePermissionRequest = JoinCode.Transport.Bridge.NdjsonPermissionRequest;
global using CoreBridgeState = JoinCode.Transport.Bridge.BridgeState;
global using FakeTimeProvider = Microsoft.Extensions.Time.Testing.FakeTimeProvider;
global using ServiceLifetime = JoinCode.Abstractions.Attributes.ServiceLifetime;