global using System.Collections.Frozen;
global using System.Diagnostics.CodeAnalysis;
global using System.Text.RegularExpressions;
global using JoinCode.CodeIndex.Ast;
global using JoinCode.CodeIndex.Persistence;
global using JoinCode.CodeIndex.Threading;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Clock;
global using JoinCode.Abstractions.CodeIndex;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Security.Shell;
global using Infrastructure.Utils.IO;
global using Infrastructure.Utils.System;
global using TreeSitter;
global using System.Xml.Linq;
global using Range = System.Range;
