<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <ProjectType>test</ProjectType>
  <RootNamespace>JoinCode.Gui.Tests</RootNamespace>
    <AssemblyName>JoinCode.Gui.Tests</AssemblyName>
    <NoWarn>$(NoWarn);NU1903;xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)app/gui/JoinCodeGui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Remove="xunit" />
    <PackageReference Remove="Xunit.SkippableFact" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>