global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Hooks;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Policy;
global using JoinCode.Abstractions.Pipeline;
global using JoinCode.Abstractions.Prompts;
global using PolicyRule = Core.Policy.PolicyRule;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Security.Scanning;
global using JoinCode.Abstractions.Security.Shell;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.ChatCommands;
global using JoinCode.Abstractions.Utils;
global using Core.Configuration;
global using Core.Configuration.Providers;
global using Core.Configuration.Remote;
global using Core.Hooks.Configuration;
global using Core.Hooks.Events;
global using Core.Hooks.Execution;
global using JoinCode.Abstractions.Hooks.Session;
global using Core.Hooks.Session;
global using Core.Hooks.ToolPermission.Handlers;
global using Core.Hooks.ToolPermission;
global using Core.Hooks;
global using Core.Hooks.Lifecycle;
global using Core.Permission;
global using Core.Permission.Services;
global using Core.Plugins;
global using Core.Policy;
global using Core.Security.Constants;
global using Core.Security.Interceptors;
global using Core.Security.Scanners;
global using Core.Security.Services;
global using Core.Utils;
global using UtilsPermissionCheckResult = JoinCode.Abstractions.Security.Permission.PermissionCheckResult;
global using ToolPermissionCheckResult = JoinCode.Abstractions.Security.Permission.ToolPermissionCheckResult;
global using JoinCode.Abstractions.Security.Permission;

global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Logging.Console;
global using Microsoft.Extensions.Options;
global using Moq;
global using PermissionResult = JoinCode.Abstractions.Security.PermissionResult;
global using System.ComponentModel.DataAnnotations;
global using System.Text.Json;
global using System.Runtime.CompilerServices;
global using Testing.Common;
global using Infrastructure.Localization;
global using Infrastructure.Pipeline;
global using IO.FileSystem;
global using Microsoft.Extensions.Time.Testing;
global using Xunit;
global using ValidationResult = Structura.Primitives.ValidationResult;
