<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <ProjectType>library</ProjectType>
  <AllowPack>true</AllowPack>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="JoinCode.AsyncLock.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)gen/enum_metadata.generator/EnumMetadata.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
