global using System.Runtime.CompilerServices;
global using Infrastructure.Localization;
global using Infrastructure.Pipeline;
global using Xunit;
global using Xunit.Abstractions;
global using Moq;
global using FluentAssertions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using System.Text;
global using System.Text.Json;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Brain.Context.Hierarchy;
global using JoinCode.Abstractions.Brain.Context.Compression;
global using JoinCode.Abstractions.Brain.Context.Resolution;
global using JoinCode.Abstractions.Brain.Planning;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Interfaces.Context;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Plan;
global using JoinCode.Abstractions.Models.Search;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Skill;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Models.Todo;
global using JoinCode.Abstractions.Pipeline;
global using JoinCode.Abstractions.Prompts;
global using JoinCode.Abstractions.Security;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using Core.Configuration;
global using Core.Context;
global using Core.Context.Collapse;
global using Core.Context.Compact;
global using Core.Context.Compression;
global using Core.Context.Resolution;
global using JoinCode.Abstractions.LLM.Execution;
global using JoinCode.Abstractions.Models.Features;
global using Core.CostTracking.FeatureFlags;
global using Core.CostTracking;
global using CoreCostTracking = Core.CostTracking;
global using CostTracker = Core.CostTracking.CostTracker;
global using RetryConfig = Core.Configuration.RetryConfig;
global using Api.LLM;
global using Core.Planning;
global using Core.Plugins;
global using Core.Prompts;
global using Core.Prompts.Sections;
global using Core.Prompts.Services;
global using Core.Prompts.Templates.Memory;
global using Core.Prompts.Templates.System;
global using Core.Prompts.Utils;
global using Core.Query;
global using Core.Query.BudgetAnalysis;
global using Core.Query.Snip;
global using Core.Query.StopHooks;
global using Core.Query.Transitions;
global using Core.Query.UsdBudget;
global using Core.Telemetry;

global using IO;
global using IO.FileSystem;
global using IO.Services;
global using ReferenceResolver = Core.Context.Resolution.ReferenceResolver;
global using ICostTracker = JoinCode.Abstractions.Interfaces.ICostTracker;
global using TokenConsumption = Core.Query.TokenConsumption;
global using StopHookContext = Core.Query.StopHooks.StopHookContext;
global using StopHookResult = Core.Query.StopHooks.StopHookResult;
global using StreamEvent = JoinCode.Abstractions.LLM.Chat.StreamEvent;
global using TranscriptEntry = JoinCode.Abstractions.LLM.Chat.TranscriptEntry;
global using Testing.Common;
global using Testing.Common.Services;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using McpClient;
