namespace JoinCode.Abstractions.Utils;

/// <summary>
/// 工具分类枚举 — 对齐 [McpToolHandler("category")] 的字符串值为编译时安全枚举
/// </summary>
public enum ToolCategory
{
    [EnumValue("web")] Web,
    [EnumValue("mcp_client")] McpClient,
    [EnumValue("skill")] Skill,
    [EnumValue("build")] Build,
    [EnumValue("analytics")] Analytics,
    [EnumValue("cron")] Cron,
    [EnumValue("goal")] Goal,
    [EnumValue("lsp")] Lsp,
    [EnumValue("code_analysis")] CodeAnalysis,
    [EnumValue("code_generation")] CodeGeneration,
    [EnumValue("code_index")] CodeIndex,
    [EnumValue("agent")] Agent,
    [EnumValue("team")] Team,
    [EnumValue("search")] Search,
    [EnumValue("step_evidence")] StepEvidence,
    [EnumValue("file")] File,
    [EnumValue("peers")] Peers,
    [EnumValue("pr_subscription")] PrSubscription,
    [EnumValue("REPL")] Repl,
    [EnumValue("terminal")] Terminal,
    [EnumValue("vcr")] Vcr,
    [EnumValue("task")] Task,
    [EnumValue("plan")] Plan,
    [EnumValue("sleep")] Sleep,
    [EnumValue("policy")] Policy,
    [EnumValue("context")] Context,
    [EnumValue("monitor")] Monitor,
    [EnumValue("snip")] Snip,
    [EnumValue("file_transfer")] FileTransfer,
    [EnumValue("voice")] Voice,
    [EnumValue("remote_trigger")] RemoteTrigger,
    [EnumValue("notification")] Notification,
    [EnumValue("browser")] Browser,
    [EnumValue("config")] Config,
    [EnumValue("git")] Git,
    [EnumValue("mcp_auth")] McpAuth,
    [EnumValue("shell")] Shell,
    [EnumValue("notebook")] Notebook,
    [EnumValue("code_execution")] CodeExecution,
    [EnumValue("powershell")] PowerShell,
    [EnumValue("todo")] Todo,
    [EnumValue("memory")] Memory,
    [EnumValue("structured_output")] StructuredOutput,
    [EnumValue("permission")] Permission,
    [EnumValue("worktree")] Worktree,
    [EnumValue("workflow")] Workflow,
    [EnumValue("interaction")] Interaction,
    [EnumValue("brief")] Brief,
    [EnumValue("mcp_resource")] McpResource,
}
