using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DangerCommand.Generator;

/// <summary>
/// 扫描 [DangerCommand] 特性标注的 const string 字段,生成 DangerousCommandCatalog.Commands 字典
/// </summary>
[Generator]
public sealed class DangerCommandGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "JoinCode.Abstractions.Security.Shell.DangerCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandInfos = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var attrSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
                if (attrSymbol is null) return ImmutableArray<CommandInfo>.Empty;

                var results = new List<CommandInfo>();
                VisitNamespaces(compilation.GlobalNamespace, attrSymbol, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(commandInfos, static (ctx, infos) =>
        {
            if (infos.Length == 0) return;
            GenerateCommands(ctx, infos);
        });
    }

    private static void VisitNamespaces(INamespaceSymbol namespaceSymbol, INamedTypeSymbol attrSymbol, List<CommandInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, attrSymbol, results);
            else if (member is INamedTypeSymbol typeSymbol)
                ScanTypeFields(typeSymbol, attrSymbol, results);
        }
    }

    private static void ScanTypeFields(INamedTypeSymbol typeSymbol, INamedTypeSymbol attrSymbol, List<CommandInfo> results)
    {
        foreach (var field in typeSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            var attr = field.GetAttributes().FirstOrDefault(a =>
                SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol));
            if (attr is null) continue;

            var commandName = field.ConstantValue as string;
            if (string.IsNullOrEmpty(commandName)) continue;

            var riskEnum = attr.ConstructorArguments.ElementAtOrDefault(0);
            var levelEnum = attr.ConstructorArguments.ElementAtOrDefault(1);
            var description = attr.ConstructorArguments.ElementAtOrDefault(2).Value as string ?? "";

            var riskName = GetEnumMemberName(riskEnum, "None");
            var levelName = GetEnumMemberName(levelEnum, "Unknown");

            results.Add(new CommandInfo(commandName!, riskName, levelName, description));
        }
    }

    private static void GenerateCommands(SourceProductionContext context, ImmutableArray<CommandInfo> infos)
    {
        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using JoinCode.Abstractions.Security.Shell;");
        sb.AppendLine();
        sb.AppendLine("namespace Core.Security.DangerClassification;");
        sb.AppendLine();
        sb.AppendLine("public static partial class DangerousCommandCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    internal static FrozenDictionary<string, CommandEntry> BuildGeneratedCommands()");
        sb.AppendLine("    {");
        sb.AppendLine("        var entries = new Dictionary<string, CommandEntry>(StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        foreach (var info in infos)
        {
            var escapedDesc = info.Description.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"            [\"{info.Name}\"] = new(\"{info.Name}\", CommandRisk.{info.RiskName}, CommandDangerLevel.{info.LevelName}, \"{escapedDesc}\"),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("        return entries.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("DangerousCommandCatalog.GeneratedCommands.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetEnumMemberName(TypedConstant enumConstant, string defaultValue)
    {
        if (enumConstant.Value is null) return defaultValue;
        if (enumConstant.Type is not INamedTypeSymbol enumType) return defaultValue;
        var enumValue = (int)enumConstant.Value;
        foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.HasConstantValue && (int)field.ConstantValue! == enumValue)
                return field.Name;
        }
        return defaultValue;
    }

    private sealed class CommandInfo
    {
        public string Name { get; }
        public string RiskName { get; }
        public string LevelName { get; }
        public string Description { get; }
        public CommandInfo(string name, string riskName, string levelName, string description)
        {
            Name = name;
            RiskName = riskName;
            LevelName = levelName;
            Description = description;
        }
    }
}
