global using Core.Utils;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Entity;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Localization;
global using JoinCode.Abstractions.Models;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using PuppeteerSharp;
global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using ServiceLifetime = JoinCode.Abstractions.Attributes.ServiceLifetime;