
namespace CliOption.Generator;

/// <summary>
/// 命令行选项源码生成器 — 扫描 [CliOption] 特性，自动生成 ParseResult + Parser 代码
/// </summary>
[Generator]
public sealed class CliOptionGenerator : IIncrementalGenerator
{
    private const string CliOptionAttributeFullName = "JoinCode.Abstractions.Attributes.CliOptionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumInfos = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var cliOptionAttr = compilation.GetTypeByMetadataName(CliOptionAttributeFullName);
                if (cliOptionAttr is null)
                    return ImmutableArray<CliEnumInfo>.Empty;

                var results = new List<CliEnumInfo>();
                VisitNamespaces(compilation.GlobalNamespace, compilation.Assembly, cliOptionAttr, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(enumInfos, static (ctx, enums) =>
        {
            foreach (var enumInfo in enums)
            {
                GenerateParser(ctx, enumInfo);
            }
        });
    }

    private static void VisitNamespaces(
        INamespaceSymbol namespaceSymbol,
        IAssemblySymbol currentAssembly,
        INamedTypeSymbol cliOptionAttr,
        List<CliEnumInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, currentAssembly, cliOptionAttr, results);
            else if (member is INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType
                     && SymbolEqualityComparer.Default.Equals(enumType.ContainingAssembly, currentAssembly))
            {
                var options = new List<CliOptionInfo>();
                foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
                {
                    var attr = field.GetAttributes()
                        .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, cliOptionAttr));
                    if (attr is null) continue;

                    var ctorArgs = attr.ConstructorArguments;
                    var longName = ctorArgs.ElementAtOrDefault(0).Value as string ?? $"--{field.Name.ToLowerInvariant()}";
                    var shortName = ctorArgs.ElementAtOrDefault(1).Value as string ?? "";
                    var description = ctorArgs.ElementAtOrDefault(2).Value as string ?? field.Name;

                    var acceptsValue = false;
                    var isNegation = false;
                    foreach (var named in attr.NamedArguments)
                    {
                        if (named.Key == "AcceptsValue") acceptsValue = (bool)(named.Value.Value ?? false);
                        if (named.Key == "IsNegation") isNegation = (bool)(named.Value.Value ?? false);
                    }

                    options.Add(new CliOptionInfo(
                        field.Name,
                        longName,
                        shortName,
                        description,
                        acceptsValue,
                        isNegation));
                }

                if (options.Count > 0)
                {
                    results.Add(new CliEnumInfo(
                        enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        enumType.Name,
                        enumType.ContainingNamespace.ToDisplayString(),
                        options.ToImmutableArray()));
                }
            }
        }
    }

    private static void GenerateParser(SourceProductionContext context, CliEnumInfo enumInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {enumInfo.Namespace};");
        sb.AppendLine();

        GenerateResultClass(sb, enumInfo);
        sb.AppendLine();
        GenerateParserClass(sb, enumInfo);

        context.AddSource($"{enumInfo.Name}Parser.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateResultClass(StringBuilder sb, CliEnumInfo enumInfo)
    {
        sb.AppendLine($"public sealed class {enumInfo.Name}ParseResult");
        sb.AppendLine("{");

        var nonNegationOptions = enumInfo.Options.Where(o => !o.IsNegation).ToList();
        var negationLongNames = new HashSet<string>(enumInfo.Options.Where(o => o.IsNegation).Select(o => o.LongName));

        foreach (var opt in nonNegationOptions)
        {
            var fieldName = ToFieldName(opt.Name);
            var hasNegation = negationLongNames.Contains("--no-" + opt.LongName.Substring(2));
            if (opt.AcceptsValue)
            {
                sb.AppendLine($"    /// <summary>{opt.Description}</summary>");
                sb.AppendLine($"    public string? {fieldName} {{ get; init; }}");
            }
            else if (hasNegation)
            {
                sb.AppendLine($"    /// <summary>{opt.Description}</summary>");
                sb.AppendLine($"    public bool? {fieldName} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"    /// <summary>{opt.Description}</summary>");
                sb.AppendLine($"    public bool {fieldName} {{ get; init; }}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>解析错误信息</summary>");
        sb.AppendLine("    public string? Error { get; init; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>是否有错误</summary>");
        sb.AppendLine("    public bool HasError => !string.IsNullOrEmpty(Error);");

        sb.AppendLine("}");
    }

    private static void GenerateParserClass(StringBuilder sb, CliEnumInfo enumInfo)
    {
        sb.AppendLine($"public static class {enumInfo.Name}Parser");
        sb.AppendLine("{");

        // 反向映射字典: string -> Enum
        sb.AppendLine($"    private static readonly FrozenDictionary<string, {enumInfo.FullyQualifiedName}> __argMap = new Dictionary<string, {enumInfo.FullyQualifiedName}>");
        sb.AppendLine("    {");
        foreach (var opt in enumInfo.Options)
        {
            sb.AppendLine($"        [\"{EscapeString(opt.LongName)}\"] = {enumInfo.FullyQualifiedName}.{opt.Name},");
            if (!string.IsNullOrEmpty(opt.ShortName))
            {
                sb.AppendLine($"        [\"{EscapeString(opt.ShortName)}\"] = {enumInfo.FullyQualifiedName}.{opt.Name},");
            }
        }
        sb.AppendLine("    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine();

        // Parse 方法
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 解析命令行参数");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {enumInfo.Name}ParseResult Parse(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(args);");
        sb.AppendLine();

        // 声明局部变量
        var nonNegationOptions = enumInfo.Options.Where(o => !o.IsNegation).ToList();
        var negationLongNames = new HashSet<string>(enumInfo.Options.Where(o => o.IsNegation).Select(o => o.LongName));
        foreach (var opt in nonNegationOptions)
        {
            var fieldName = ToFieldName(opt.Name);
            var hasNegation = negationLongNames.Contains("--no-" + opt.LongName.Substring(2));
            if (opt.AcceptsValue)
            {
                sb.AppendLine($"        string? {ToCamelCase(fieldName)} = null;");
            }
            else if (hasNegation)
            {
                sb.AppendLine($"        bool? {ToCamelCase(fieldName)} = null;");
            }
            else
            {
                sb.AppendLine($"        var {ToCamelCase(fieldName)} = false;");
            }
        }
        sb.AppendLine("        string? error = null;");
        sb.AppendLine();

        // 解析循环
        sb.AppendLine("        for (var i = 0; i < args.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (!__argMap.TryGetValue(args[i], out var cliArg)) {{ if (args[i].StartsWith('-')) {{ error = $\"Unknown option: {{args[i]}}\"; break; }} continue; }}");
        sb.AppendLine();
        sb.AppendLine("            switch (cliArg)");
        sb.AppendLine("            {");

        foreach (var opt in enumInfo.Options)
        {
            var fieldName = ToFieldName(opt.Name);
            var camelName = ToCamelCase(fieldName);

            sb.AppendLine($"                case {enumInfo.FullyQualifiedName}.{opt.Name}:");

            if (opt.IsNegation)
            {
                var positiveOpt = enumInfo.Options.FirstOrDefault(o => !o.IsNegation && o.LongName == "--" + opt.LongName.Substring(5));
                var positiveCamel = positiveOpt != null ? ToCamelCase(positiveOpt.Name) : ToCamelCase(ToPascalCaseFromKebab(opt.LongName.Substring(5)));
                sb.AppendLine($"                    {positiveCamel} = false;");
            }
            else if (opt.AcceptsValue)
            {
                sb.AppendLine($"                    if (i + 1 >= args.Length) {{ error = $\"{{args[i]}} requires a value\"; break; }}");
                sb.AppendLine($"                    {camelName} = args[++i];");
            }
            else
            {
                sb.AppendLine($"                    {camelName} = true;");
            }

            sb.AppendLine("                    break;");
            sb.AppendLine();
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 构造结果
        sb.AppendLine($"        return new {enumInfo.Name}ParseResult");
        sb.AppendLine("        {");
        foreach (var opt in nonNegationOptions)
        {
            var fieldName = ToFieldName(opt.Name);
            var camelName = ToCamelCase(fieldName);
            sb.AppendLine($"            {fieldName} = {camelName},");
        }
        sb.AppendLine("            Error = error,");
        sb.AppendLine("        };");

        sb.AppendLine("    }");

        // GetHelpText 方法
        sb.AppendLine();
        GenerateHelpTextMethod(sb, enumInfo);

        sb.AppendLine("}");
    }

    private static void GenerateHelpTextMethod(StringBuilder sb, CliEnumInfo enumInfo)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 生成帮助文本");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string GetHelpText()");
        sb.AppendLine("    {");

        var sb2 = new StringBuilder();
        sb2.AppendLine($"Usage: {enumInfo.Name.ToLowerInvariant()} [options]");
        sb2.AppendLine();
        sb2.AppendLine("Options:");
        foreach (var opt in enumInfo.Options)
        {
            var label = string.IsNullOrEmpty(opt.ShortName)
                ? $"  {opt.LongName}"
                : $"  {opt.ShortName}, {opt.LongName}";
            if (opt.AcceptsValue) label += " <value>";
            label = label.PadRight(36);
            sb2.AppendLine($"{label}{opt.Description}");
        }

        var lines = sb2.ToString().Split('\n');
        sb.AppendLine("        return");
        var isFirst = true;
        foreach (var line in lines)
        {
            var trimmed = line.TrimEnd('\r');
            if (trimmed.Length > 0)
            {
                sb.AppendLine($"            {(isFirst ? "" : "+ ")}\"{EscapeString(trimmed)}\\n\"");
                isFirst = false;
            }
        }
        sb.AppendLine("            ;");
        sb.AppendLine("    }");
    }

    private static string ToFieldName(string enumMemberName)
    {
        if (enumMemberName.Length <= 1) return enumMemberName;
        return enumMemberName;
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length <= 1) return name.ToLowerInvariant();
        var result = char.ToLowerInvariant(name[0]) + name.Substring(1);
        return IsCSharpKeyword(result) ? "@" + result : result;
    }

    private static bool IsCSharpKeyword(string name)
    {
        switch (name)
        {
            case "abstract": case "as": case "base": case "bool": case "break":
            case "byte": case "case": case "catch": case "char": case "checked":
            case "class": case "const": case "continue": case "decimal": case "default":
            case "delegate": case "do": case "double": case "else": case "enum":
            case "event": case "explicit": case "extern": case "false": case "finally":
            case "fixed": case "float": case "for": case "foreach": case "goto":
            case "if": case "implicit": case "in": case "int": case "interface":
            case "internal": case "is": case "lock": case "long": case "namespace":
            case "new": case "null": case "object": case "operator": case "out":
            case "override": case "params": case "private": case "protected": case "public":
            case "readonly": case "ref": case "return": case "sbyte": case "sealed":
            case "short": case "sizeof": case "stackalloc": case "static": case "string":
            case "struct": case "switch": case "this": case "throw": case "true":
            case "try": case "typeof": case "uint": case "ulong": case "unchecked":
            case "unsafe": case "ushort": case "using": case "virtual": case "void":
            case "volatile": case "while":
                return true;
            default:
                return false;
        }
    }

    private static string ToPascalCaseFromKebab(string kebab)
    {
        var parts = kebab.Split('-');
        var sb2 = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            sb2.Append(char.ToUpperInvariant(part[0]));
            sb2.Append(part.Substring(1));
        }
        return sb2.ToString();
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class CliEnumInfo
    {
        public string FullyQualifiedName { get; }
        public string Name { get; }
        public string Namespace { get; }
        public ImmutableArray<CliOptionInfo> Options { get; }

        public CliEnumInfo(string fullyQualifiedName, string name, string ns, ImmutableArray<CliOptionInfo> options)
        {
            FullyQualifiedName = fullyQualifiedName;
            Name = name;
            Namespace = ns;
            Options = options;
        }
    }

    private sealed class CliOptionInfo
    {
        public string Name { get; }
        public string LongName { get; }
        public string ShortName { get; }
        public string Description { get; }
        public bool AcceptsValue { get; }
        public bool IsNegation { get; }

        public CliOptionInfo(string name, string longName, string shortName, string description, bool acceptsValue, bool isNegation)
        {
            Name = name;
            LongName = longName;
            ShortName = shortName;
            Description = description;
            AcceptsValue = acceptsValue;
            IsNegation = isNegation;
        }
    }
}
