global using FluentAssertions;
global using IO.FileSystem;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using McpToolDispatch;
global using Moq;
global using System.Collections.Frozen;
global using System.Text.Json;
global using Testing.Common;
