global using AgentMsg = JoinCode.Abstractions.Models.Agent.CoordinatorMessage;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Interfaces.Scheduling;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Agent;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Models.Shell;
global using JoinCode.Abstractions.Models.Todo;
global using JoinCode.Abstractions.Pipeline;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Tools;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.Localization;
global using Core.Agents.Coordinator;
global using Core.Agents.Interfaces;
global using Infrastructure.Pipeline;
global using Core.Scheduling;
global using Core.Scheduling.Cron;
global using Core.Scheduling.Tasks;
global using Core.Scheduling.Runtime;
global using IMcpClient = JoinCode.Abstractions.Mcp.Client.IMcpClient;
global using McpListToolsResult = JoinCode.Abstractions.Models.OperationResult<System.Collections.Generic.IReadOnlyList<JoinCode.Abstractions.Tools.ToolInfo>>;
global using McpListResourcesResult = JoinCode.Abstractions.Models.OperationResult<System.Collections.Generic.IReadOnlyList<JoinCode.Abstractions.Mcp.Protocol.McpResource>>;
global using McpClient;
global using JoinCode.Abstractions.Mcp.Protocol;
global using McpResource = JoinCode.Abstractions.Mcp.Protocol.McpResource;
global using JoinCode.Abstractions.Mcp.Registry;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Time.Testing;
global using Moq;
global using System.Runtime.CompilerServices;
global using TaskState = JoinCode.Abstractions.Models.Task.TaskStatus;
global using TodoPriority = JoinCode.Abstractions.Models.Todo.TodoPriority;
global using Testing.Common;
global using Testing.Common.Services;
global using ToolContent = JoinCode.Abstractions.Tools.ToolContent;
global using Xunit;
global using Xunit.Abstractions;
