global using Core.Utils;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Entity;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Telemetry;
global using JoinCode.Abstractions.Utils;
global using JoinCode.Abstractions.LLM;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using ServiceLifetime = JoinCode.Abstractions.Attributes.ServiceLifetime;
global using IAsyncDisposable = System.IAsyncDisposable;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Threading.Channels;
