
namespace McpToolHandlers.Generator;

[Generator]
public sealed class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string ChatCommandAttributeFullName = "JoinCode.ChatCommands.ChatCommandAttribute";
    private const string IChatCommandFullName = "JoinCode.ChatCommands.IChatCommand";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandTypes = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var chatCommandAttr = compilation.GetTypeByMetadataName(ChatCommandAttributeFullName);

                if (chatCommandAttr is null)
                    return ImmutableArray<CommandInfo>.Empty;

                var results = new List<CommandInfo>();
                VisitNamespaces(compilation.GlobalNamespace, chatCommandAttr, results);
                return results.ToImmutableArray();
            })
            .Collect();

        context.RegisterSourceOutput(commandTypes, static (ctx, commands) =>
        {
            GenerateRegistrationCode(ctx, commands);
        });
    }

    private static void VisitNamespaces(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol? chatCommandAttr,
        List<CommandInfo> results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
                VisitNamespaces(childNamespace, chatCommandAttr, results);
            else if (member is INamedTypeSymbol typeSymbol && chatCommandAttr is not null)
            {
                var attr = typeSymbol.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, chatCommandAttr));
                if (attr is not null)
                {
                    var name = attr.NamedArguments.FirstOrDefault(n => n.Key == "Name").Value.Value as string
                        ?? attr.ConstructorArguments.ElementAtOrDefault(0).Value as string
                        ?? typeSymbol.Name;

                    // 提取 Category — 特性解耦，每个命令自己声明分类
                    var categoryValue = attr.NamedArguments.FirstOrDefault(n => n.Key == "Category").Value;
                    string? categoryEnumName = null;
                    if (!categoryValue.IsNull)
                    {
                        // 从枚举值获取成员名（如 ChatCommandCategory.Session → "Session"）
                        if (categoryValue.Value is int categoryInt && categoryInt >= 0)
                        {
                            // 遍历枚举成员找到匹配的名称
                            var categoryType = categoryValue.Type;
                            if (categoryType is INamedTypeSymbol enumType)
                            {
                                foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
                                {
                                    if (field.ConstantValue is int fieldValue && fieldValue == categoryInt)
                                    {
                                        categoryEnumName = field.Name;
                                        break;
                                    }
                                }
                            }
                        }
                    }

                    results.Add(new CommandInfo(
                        typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        name,
                        CommandType.ChatCommand,
                        categoryEnumName));
                }
            }
        }
    }

    private static void GenerateRegistrationCode(SourceProductionContext context, ImmutableArray<CommandInfo> commands)
    {
        var validCommands = commands.OrderBy(c => c.Name).ToList();

        if (validCommands.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using JoinCode.ChatCommands;");
        sb.AppendLine();
        sb.AppendLine("namespace JoinCode;");
        sb.AppendLine();
        sb.AppendLine("public static partial class GeneratedCommandRegistration");
        sb.AppendLine("{");

        var chatCommands = validCommands.Where(c => c.Type == CommandType.ChatCommand).ToList();

        if (chatCommands.Count > 0)
        {
            GenerateRegisterChatCommandsMethod(sb, chatCommands);
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource("GeneratedCommandRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateRegisterChatCommandsMethod(StringBuilder sb, List<CommandInfo> commands)
    {
        sb.AppendLine("    public static void RegisterAllChatCommands(ChatCommandRegistry registry)");
        sb.AppendLine("    {");

        foreach (var cmd in commands)
        {
            sb.AppendLine($"        registry.Register(new {cmd.FullyQualifiedName}());");

            // 生成 SetCategory 调用 — 特性解耦，源码生成器自动提取
            if (cmd.CategoryEnumName is not null)
            {
                sb.AppendLine($"        registry.SetCategory(\"{EscapeString(cmd.Name)}\", JoinCode.Abstractions.Utils.ChatCommandCategory.{cmd.CategoryEnumName});");
            }
        }

        sb.AppendLine("    }");
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private enum CommandType
    {
        ChatCommand
    }

    private sealed class CommandInfo
    {
        public string FullyQualifiedName { get; }
        public string Name { get; }
        public CommandType Type { get; }
        public string? CategoryEnumName { get; }

        public CommandInfo(string fullyQualifiedName, string name, CommandType type, string? categoryEnumName = null)
        {
            FullyQualifiedName = fullyQualifiedName;
            Name = name;
            Type = type;
            CategoryEnumName = categoryEnumName;
        }
    }
}
