<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectType>test</ProjectType>
    <OutputType>Exe</OutputType>
    <RootNamespace>CodeIndexBenchmarks</RootNamespace>
    <AssemblyName>CodeIndex.Benchmarks</AssemblyName>
    <ExcludeTestSdk>true</ExcludeTestSdk>
    <ExcludeJccAnalyzers>true</ExcludeJccAnalyzers>
    <IsAotCompatible>false</IsAotCompatible>
    <PublishAot>false</PublishAot>
    <TrimMode></TrimMode>
    <NoWarn>$(NoWarn);VSTHRD200</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)server/code_index/CodeIndex.csproj" />
  </ItemGroup>

</Project>
