<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fsm.Generator.Tests</RootNamespace>
    <AssemblyName>JoinCode.Fsm.Generator.Tests</AssemblyName>
    <Description>Fsm 源码生成器单元测试</Description>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <PublishAot>false</PublishAot>
    <ExcludeJccAnalyzers>true</ExcludeJccAnalyzers>
    <NoWarn>$(NoWarn);NU1701;NU1608;JCC3007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)generators\Fsm.Generator\src\Fsm.Generator.csproj" />
    <ProjectReference Include="$(RepoRoot)foundation\Abstractions\Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNETTestSdkVersion)" />
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertionsVersion)" />
    <PackageReference Include="xunit" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVisualStudioVersion)">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
