global using System.Runtime.CompilerServices;
global using Infrastructure.Localization;
global using JoinCode.Abstractions.Attributes;
global using JoinCode.Abstractions.Configuration;
global using JoinCode.Abstractions.Configuration.AppData;
global using JoinCode.Abstractions.Configuration.Providers;
global using JoinCode.Abstractions.Configuration.Execution;
global using JoinCode.Abstractions.Configuration.Llm;
global using JoinCode.Abstractions.Configuration.Settings;
global using JoinCode.Abstractions.Exceptions;
global using JoinCode.Abstractions.Interfaces;
global using JoinCode.Abstractions.LLM;
global using JoinCode.Abstractions.LLM.Chat;
global using JoinCode.Abstractions.Models;
global using JoinCode.Abstractions.Models.Runtime;
global using JoinCode.Abstractions.Models.Skill;
global using JoinCode.Abstractions.Models.Task;
global using JoinCode.Abstractions.Models.StepEvidence;
global using JoinCode.Abstractions.Security.Shell;
global using JoinCode.Abstractions.State;
global using JoinCode.Abstractions.Utils;
global using Core.Memdir;
global using JoinCode.Vault.DependencyInjection;

global using IO;
global using IO.FileSystem;
global using IO.Services;
global using Memdir.Sync;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Services.Notification;
global using Services.StepEvidence.ToolHandlers;
global using Services.UserInteraction;
global using State;
global using System.Collections.Immutable;
global using StreamEvent = JoinCode.Abstractions.LLM.Chat.StreamEvent;
global using TaskState = JoinCode.Abstractions.Models.Task.TaskStatus;
global using Testing.Common;
global using Testing.Common.Services;
global using TranscriptEntry = JoinCode.Abstractions.LLM.Chat.TranscriptEntry;
global using TranscriptSummary = JoinCode.Abstractions.LLM.Chat.TranscriptSummary;
global using Xunit.Abstractions;
