namespace McpProtocol.Contracts;

[JsonSerializable(typeof(JsonRpcId))]
[JsonSerializable(typeof(JsonRpcRequest))]
[JsonSerializable(typeof(JsonRpcResponse))]
[JsonSerializable(typeof(JsonRpcError))]
[JsonSerializable(typeof(JsonRpcNotification))]
[JsonSerializable(typeof(InitializeRequestParams))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(ClientCapabilities))]
[JsonSerializable(typeof(ServerCapabilities))]
[JsonSerializable(typeof(ToolsCapability))]
[JsonSerializable(typeof(Implementation))]
[JsonSerializable(typeof(ListToolsResult))]
[JsonSerializable(typeof(InputSchema))]
[JsonSerializable(typeof(PropertySchema))]
[JsonSerializable(typeof(Dictionary<string, PropertySchema>))]
[JsonSerializable(typeof(CallToolRequestParams))]
[JsonSerializable(typeof(CallToolResult))]
[JsonSerializable(typeof(ToolContent))]
[JsonSerializable(typeof(List<ToolContent>))]
[JsonSerializable(typeof(ToolDefinition))]
[JsonSerializable(typeof(List<ToolDefinition>))]
[JsonSerializable(typeof(McpResource))]
[JsonSerializable(typeof(List<McpResource>))]
[JsonSerializable(typeof(McpResourceContent))]
[JsonSerializable(typeof(List<McpResourceContent>))]
[JsonSerializable(typeof(McpResourcesListResponse))]
[JsonSerializable(typeof(McpResourceReadResponse))]
[JsonSerializable(typeof(McpPrompt))]
[JsonSerializable(typeof(List<McpPrompt>))]
[JsonSerializable(typeof(McpPromptArgument))]
[JsonSerializable(typeof(List<McpPromptArgument>))]
[JsonSerializable(typeof(McpPromptMessage))]
[JsonSerializable(typeof(McpMessage))]
[JsonSerializable(typeof(List<McpMessage>))]
[JsonSerializable(typeof(McpMessageContent))]
[JsonSerializable(typeof(McpPromptsListResponse))]
[JsonSerializable(typeof(McpPromptGetResponse))]
[JsonSerializable(typeof(ResourcesCapability))]
[JsonSerializable(typeof(PromptsCapability))]
[JsonSerializable(typeof(LoggingCapability))]
[JsonSerializable(typeof(PingResult))]
[JsonSerializable(typeof(LoggingSetLevelRequestParams))]
[JsonSerializable(typeof(McpResourceReadRequestParams))]
[JsonSerializable(typeof(McpPromptGetRequestParams))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(ElicitRequestParams))]
[JsonSerializable(typeof(ElicitResult))]
[JsonSerializable(typeof(ElicitSchema))]
[JsonSerializable(typeof(ElicitSchemaProperty))]
[JsonSerializable(typeof(Dictionary<string, ElicitSchemaProperty>))]
[JsonSerializable(typeof(ElicitationCompleteNotificationParams))]
[JsonSerializable(typeof(Dictionary<string, JsonElement?>))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(string))]

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    AllowTrailingCommas = true,
    ReadCommentHandling = JsonCommentHandling.Skip,
    PropertyNameCaseInsensitive = true)]
public partial class McpJsonContext : JsonSerializerContext
{
}
