name: CI/CD

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.xxx/**'
      - 'LICENSE'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml

  unit-tests:
    needs: build
    uses: ./.github/workflows/ci-unit-tests.yml

  integration:
    needs: build
    uses: ./.github/workflows/ci-integration.yml

  e2e:
    needs: build
    uses: ./.github/workflows/ci-e2e.yml
